version: '2'
services:
    ebweb-app:
        image: ebweb
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://ebweb-mssql:1433;database=ebweb
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ebweb-mssql:
        extends:
            file: mssql.yml
            service: ebweb-mssql
