import * as moment from 'moment';

export const PP_SERVICE_TYPE = {
    PP_SERVICE_TYPE_GROUP_ID: 24,
    PP_SERVICE_UNPAID: '240',
    PP_SERVICE_CASH: '241',
    PP_SERVICE_PAYMENT_ORDER: '242',
    PP_SERVICE_TRANSFER_SEC: '243',
    PP_SERVICE_CREDIT_CARD: '244',
    PP_SERVICE_CASH_SEC: '245',
    PP_SERVICE_UNPAID_NUM: 240,
    PP_SERVICE_CASH_NUM: 241,
    PP_SERVICE_PAYMENT_ORDER_NUM: 242,
    PP_SERVICE_TRANSFER_SEC_NUM: 243,
    PP_SERVICE_CREDIT_CARD_NUM: 244,
    PP_SERVICE_CASH_SEC_NUM: 245
};

export const ACCOUNT_TYPE = {
    DEBIT_ACCOUNT: 0,
    CREDIT_ACCOUNT: 1
};

export const GEN_CODE_TYPE_GROUP = {
    PP_SERVICE_LICENSE: 24,
    MC_PAYMENT: 11,
    PAYMENT_ORDER: 12,
    TRANSFER_SEC: 13,
    CASH_SEC: 14,
    CREDIT_CARD: 17
};

// Chuyen tu String DDMMYYYY -> YYYY-MM-DD
export const formatStrDate = (dateString: string): string => {
    const result = moment(dateString, 'DD/MM/YYYY').format('DD/MM/YYYY');
    if (result === 'Invalid date') {
        return '';
    }
    return result;
};

export const UpdateDataMessages = {
    SAVE_SUCCESS: 'SAVE_SUCCESS',
    UPDATE_SUCCESS: 'UPDATE_SUCCESS',
    EXPENSIVE_ITEM_HAS_CHILD: 'EXPENSIVE_ITEM_HAS_CHILD',
    CANNOT_UPDATE_OTHER_NO_BOOK: 'CANNOT_UPDATE_OTHER_NO_BOOK',
    DUPLICATE_OTHER_NO_BOOK: 'DUPLICATE_OTHER_NO_BOOK',
    CANNOT_UPDATE_NO_BOOK: 'CANNOT_UPDATE_NO_BOOK',
    DUPLICATE_NO_BOOK: 'DUPLICATE_NO_BOOK',
    DUPLICATE_NO_BOOK_RS: 'DUPLICATE_NO_BOOK_RS',
    CANNOT_UPDATE_NO_BOOK_RS: 'CANNOT_UPDATE_NO_BOOK_RS',
    CURRENT_USER_IS_NOT_PRESENT: 'CURRENT_USER_IS_NOT_PRESENT',
    DATE_NULL: 'DATE_NULL',
    PP_SERVICE_IS_NOT_PRESET: 'PP_SERVICE_IS_NOT_PRESET',
    MC_PAYMENT_IS_NOT_PRESET: 'MC_PAYMENT_IS_NOT_PRESET',
    MB_TELLER_PAPER_IS_NOT_PRESET: 'MB_TELLER_PAPER_IS_NOT_PRESET',
    MB_CREDIT_CARD_IS_NOT_PRESET: 'MB_CREDIT_CARD_IS_NOT_PRESET',
    DELETE_SUCCESS: 'DELETE_SUCCESS',
    HAD_REFERENCE_AND_PAID: 'HAD_REFERENCE_AND_PAID',
    HAD_REFERENCE: 'HAD_REFERENCE',
    HAD_PAID: 'HAD_PAID',
    RSI_ERROR: 'RSI_ERROR',
    PPINVOICE_NOT_FOUND: 'PPINVOICE_NOT_FOUND',
    PPINVOICE_USED: 'PPINVOICE_USED',
    IS_FIST_ITEM: 'IS_FIST_ITEM',
    IS_LAST_ITEM: 'IS_LAST_ITEM',
    NO_BOOK_NULL: 'NO_BOOK_NULL',
    NO_BOOK_RSI_NULL: 'NO_BOOK_RSI_NULL',
    NO_BOOK_OTHER_NULL: 'NO_BOOK_OTHER_NULL',
    NOTHING: 'NOTHING',
    STOCK_TRUE: 'STOCK_TRUE',
    STOCK_FALSE: 'STOCK_FALSE',
    QUANTITY_RECEIPT_GREATER_THAN: 'QUANTITY_RECEIPT_GREATER_THAN',
    NOT_FOUND: 'NOT_FOUND',
    DUPLICATE_PP_SERVICE: 'updateReceipt24',
    DUPLICATE_MC_PAYMENT: 'updateReceipt11',
    DUPLICATE_PAYMENT_ORDER: 'updateReceipt12',
    DUPLICATE_TRANSFER_SEC: 'updateReceipt13',
    DUPLICATE_CASH_SEC: 'updateReceipt14',
    DUPLICATE_CREDIT_CARD: 'updateReceipt17',
    SUCCESS: 'SUCCESS',
    DUPLICATE: 'DUPLICATE',
    NO_VOUCHER_LIMITED: 'noVoucherLimited',
    DETAIL_CODE_INVALID: 'detailCodeInvalid',
    POSTDATE_INVALID: 'postdateInvalid'
};
