-- Author Hautv
CREATE VIEW [dbo].[ViewVoucherNoDetailForCloseBook]
AS
    SELECT NEWID()           AS ID,
           a.ID              as RefID,
           a.MCPaymentID     as RefParentID,
           a.CreditAccount,
           a.DebitAccount,
           a.BankAccountDetailID,
           ba.BankAccount,
           ba.BankName,
           a.Amount,
           a.AmountOriginal,
           NULL              as VATRate,
           NULL              as VATAccount,
           NULL              as DeductionDebitAccount,
           NULL              as VATAmount,
           NULL              as VATAmountOriginal,
           NULL              as DiscountRate,
           NULL              as DiscountAccount,
           NULL              as DiscountAmount,
           NULL              as DiscountAmountOriginal,
           NULL              as ExportTaxAmount,
           NULL              as ExportTaxAmountAccount,
           NULL              as ExportTaxAccountCorresponding,
           a.Description,
           a.AccountingObjectID,
           d.AccountingObjectCode,
           d.AccountingObjectName,
           d.AccountingObjectAddress,
           NULL              as DebitAccountingObjectID,
           NULL              as DebitAccountingObjectCode,
           NULL              as DebitAccountingObjectName,
           NULL              as DebitAccountingObjectAddress,
           NULL              as CreditAccountingObjectID,
           NULL              as CreditAccountingObjectCode,
           NULL              as CreditAccountingObjectName,
           NULL              as CreditAccountingObjectAddress,
           NULL              as EmployeeID,
           NULL              as EmployeeCode,
           NULL              as EmployeeName,
           NULL              as MaterialGoodsID,
           NULL              as MaterialGoodsCode,
           NULL              as MaterialGoodsName,
           NULL              as RepositoryID,
           NULL              as RepositoryCode,
           NULL              as RepositoryName,
           NULL              as UnitID,
           NULL              as Quantity,
           NULL              as UnitPrice,
           NULL              as UnitPriceOriginal,
           NULL              as MainUnitID,
           NULL              as MainQuantity,
           NULL              as MainUnitPrice,
           NULL              as MainConvertRate,
           NULL              as Formula,
           NULL              as ConfrontID,
           NULL              as ConfrontDetailID,
           NULL              as PPOrderDetailId,
           NULL              as PPOrderDetailQuantity,
           NULL              as RepositoryAccount,
           NULL              as CostAccount,
           NULL              as vatDescription,
           NULL              as invoiceNo,
           NULL              as OWPrice,
           NULL              as OWAmount,
           NULL              as LotNo,
           NULL              as ExpiryDate,
           a.DepartmentID,
           a.ExpenseItemID,
           a.BudgetItemID,
           a.CostSetID,
           a.ContractID,
           a.StatisticsCodeID,
           null              as importTaxAmount,
           null              as importTaxAmountOriginal,
           null              as importTaxAccount,
           null              as specialConsumeTaxAmount,
           null              as specialConsumeTaxAmountOriginal,
           null              as specialConsumeTaxAccount,
           a.OrderPriority,
           NULL              as IsPromotion,
           NULL              as InwardAmount,
           NULL              as FromRepositoryID,
           NULL              as ToRepositoryID,
           'MCPaymentDetail' AS RefTable
    FROM MCPaymentDetail a
             left join AccountingObject d on a.AccountingObjectID = d.ID
             left join BankAccountDetail ba on ba.ID = a.BankAccountDetailID
    UNION ALL
    SELECT NEWID()           AS ID,
           a.ID              as RefID,
           a.MCReceiptID     as RefParentID,
           a.CreditAccount,
           a.DebitAccount,
           a.BankAccountDetailID,
           ba.BankAccount,
           ba.BankName,
           a.Amount,
           a.AmountOriginal,
           NULL              as VATRate,
           NULL              as VATAccount,
           NULL              as DeductionDebitAccount,
           NULL              as VATAmount,
           NULL              as VATAmountOriginal,
           NULL              as DiscountRate,
           NULL              as DiscountAccount,
           NULL              as DiscountAmount,
           NULL              as DiscountAmountOriginal,
           NULL              as ExportTaxAmount,
           NULL              as ExportTaxAmountAccount,
           NULL              as ExportTaxAccountCorresponding,
           a.Description,
           a.AccountingObjectID,
           d.AccountingObjectCode,
           d.AccountingObjectName,
           d.AccountingObjectAddress,
           NULL              as DebitAccountingObjectID,
           NULL              as DebitAccountingObjectCode,
           NULL              as DebitAccountingObjectName,
           NULL              as DebitAccountingObjectAddress,
           NULL              as CreditAccountingObjectID,
           NULL              as CreditAccountingObjectCode,
           NULL              as CreditAccountingObjectName,
           NULL              as CreditAccountingObjectAddress,
           NULL              as EmployeeID,
           NULL              as EmployeeCode,
           NULL              as EmployeeName,
           NULL              as MaterialGoodsID,
           NULL              as MaterialGoodsCode,
           NULL              as MaterialGoodsName,
           NULL              as RepositoryID,
           NULL              as RepositoryCode,
           NULL              as RepositoryName,
           NULL              as UnitID,
           NULL              as Quantity,
           NULL              as UnitPrice,
           NULL              as UnitPriceOriginal,
           NULL              as MainUnitID,
           NULL              as MainQuantity,
           NULL              as MainUnitPrice,
           NULL              as MainConvertRate,
           NULL              as Formula,
           NULL              as ConfrontID,
           NULL              as ConfrontDetailID,
           NULL              as PPOrderDetailId,
           NULL              as PPOrderDetailQuantity,
           NULL              as RepositoryAccount,
           NULL              as CostAccount,
           NULL              as vatDescription,
           NULL              as invoiceNo,
           NULL              as OWPrice,
           NULL              as OWAmount,
           NULL              as LotNo,
           NULL              as ExpiryDate,
           a.DepartmentID,
           a.ExpenseItemID,
           a.BudgetItemID,
           a.CostSetID,
           a.ContractID,
           a.StatisticsCodeID,
           null              as importTaxAmount,
           null              as importTaxAmountOriginal,
           null              as importTaxAccount,
           null              as specialConsumeTaxAmount,
           null              as specialConsumeTaxAmountOriginal,
           null              as specialConsumeTaxAccount,
           a.OrderPriority,
           NULL              as IsPromotion,
           NULL              as InwardAmount,
           NULL              as FromRepositoryID,
           NULL              as ToRepositoryID,
           'MCReceiptDetail' AS RefTable
    FROM dbo.MCReceiptDetail a
             left join AccountingObject d on a.AccountingObjectID = d.ID
             left join BankAccountDetail ba on ba.ID = a.BankAccountDetailID
/* =======================================================================*/
    UNION ALL
    SELECT NEWID()               AS ID,
           a.ID                  as RefID,
           a.MBTellerPaperID     as RefParentID,
           a.CreditAccount,
           a.DebitAccount,
           NULL                  as BankAccountDetailID,
           NULL                  as BankAccount,
           NULL                  as BankName,
           a.Amount,
           a.AmountOriginal,
           NULL                  as VATRate,
           NULL                  as VATAccount,
           NULL                  as DeductionDebitAccount,
           NULL                  as VATAmount,
           NULL                  as VATAmountOriginal,
           NULL                  as DiscountRate,
           NULL                  as DiscountAccount,
           NULL                  as DiscountAmount,
           NULL                  as DiscountAmountOriginal,
           NULL                  as ExportTaxAmount,
           NULL                  as ExportTaxAmountAccount,
           NULL                  as ExportTaxAccountCorresponding,
           a.Description,
           a.AccountingObjectID,
           d.AccountingObjectCode,
           d.AccountingObjectName,
           d.AccountingObjectAddress,
           NULL                  as DebitAccountingObjectID,
           NULL                  as DebitAccountingObjectCode,
           NULL                  as DebitAccountingObjectName,
           NULL                  as DebitAccountingObjectAddress,
           NULL                  as CreditAccountingObjectID,
           NULL                  as CreditAccountingObjectCode,
           NULL                  as CreditAccountingObjectName,
           NULL                  as CreditAccountingObjectAddress,
           NULL                  as EmployeeID,
           NULL                  as EmployeeCode,
           NULL                  as EmployeeName,
           NULL                  as MaterialGoodsID,
           NULL                  as MaterialGoodsCode,
           NULL                  as MaterialGoodsName,
           NULL                  as RepositoryID,
           NULL                  as RepositoryCode,
           NULL                  as RepositoryName,
           NULL                  as UnitID,
           NULL                  as Quantity,
           NULL                  as UnitPrice,
           NULL                  as UnitPriceOriginal,
           NULL                  as MainUnitID,
           NULL                  as MainQuantity,
           NULL                  as MainUnitPrice,
           NULL                  as MainConvertRate,
           NULL                  as Formula,
           NULL                  as ConfrontID,
           NULL                  as ConfrontDetailID,
           NULL                  as PPOrderDetailId,
           NULL                  as PPOrderDetailQuantity,
           NULL                  as RepositoryAccount,
           NULL                  as CostAccount,
           NULL                  as vatDescription,
           NULL                  as invoiceNo,
           NULL                  as OWPrice,
           NULL                  as OWAmount,
           NULL                  as LotNo,
           NULL                  as ExpiryDate,
           a.DepartmentID,
           a.ExpenseItemID,
           a.BudgetItemID,
           a.CostSetID,
           a.ContractID,
           a.StatisticsCodeID,
           null                  as importTaxAmount,
           null                  as importTaxAmountOriginal,
           null                  as importTaxAccount,
           null                  as specialConsumeTaxAmount,
           null                  as specialConsumeTaxAmountOriginal,
           null                  as specialConsumeTaxAccount,
           a.OrderPriority,
           NULL                  as IsPromotion,
           NULL                  as InwardAmount,
           NULL                  as FromRepositoryID,
           NULL                  as ToRepositoryID,
           'MBTellerPaperDetail' AS RefTable
    FROM dbo.MBTellerPaperDetail a
             left join AccountingObject d on d.ID = a.AccountingObjectID
/* =======================================================================*/
    UNION ALL
    SELECT NEWID()              AS ID,
           a.ID                 as RefID,
           a.MBCreditCardID     as RefParentID,
           a.CreditAccount,
           a.DebitAccount,
           NULL                 as BankAccountDetailID,
           NULL                 as BankAccount,
           NULL                 as BankName,
           a.Amount,
           a.AmountOriginal,
           NULL                 as VATRate,
           NULL                 as VATAccount,
           NULL                 as DeductionDebitAccount,
           NULL                 as VATAmount,
           NULL                 as VATAmountOriginal,
           NULL                 as DiscountRate,
           NULL                 as DiscountAccount,
           NULL                 as DiscountAmount,
           NULL                 as DiscountAmountOriginal,
           NULL                 as ExportTaxAmount,
           NULL                 as ExportTaxAmountAccount,
           NULL                 as ExportTaxAccountCorresponding,
           a.Description,
           a.AccountingObjectID,
           d.AccountingObjectCode,
           d.AccountingObjectName,
           d.AccountingObjectAddress,
           NULL                 as DebitAccountingObjectID,
           NULL                 as DebitAccountingObjectCode,
           NULL                 as DebitAccountingObjectName,
           NULL                 as DebitAccountingObjectAddress,
           NULL                 as CreditAccountingObjectID,
           NULL                 as CreditAccountingObjectCode,
           NULL                 as CreditAccountingObjectName,
           NULL                 as CreditAccountingObjectAddress,
           NULL                 as EmployeeID,
           NULL                 as EmployeeCode,
           NULL                 as EmployeeName,
           NULL                 as MaterialGoodsID,
           NULL                 as MaterialGoodsCode,
           NULL                 as MaterialGoodsName,
           NULL                 as RepositoryID,
           NULL                 as RepositoryCode,
           NULL                 as RepositoryName,
           NULL                 as UnitID,
           NULL                 as Quantity,
           NULL                 as UnitPrice,
           NULL                 as UnitPriceOriginal,
           NULL                 as MainUnitID,
           NULL                 as MainQuantity,
           NULL                 as MainUnitPrice,
           NULL                 as MainConvertRate,
           NULL                 as Formula,
           NULL                 as ConfrontID,
           NULL                 as ConfrontDetailID,
           NULL                 as PPOrderDetailId,
           NULL                 as PPOrderDetailQuantity,
           NULL                 as RepositoryAccount,
           NULL                 as CostAccount,
           NULL                 as vatDescription,
           NULL                 as invoiceNo,
           NULL                 as OWPrice,
           NULL                 as OWAmount,
           NULL                 as LotNo,
           NULL                 as ExpiryDate,
           a.DepartmentID,
           a.ExpenseItemID,
           a.BudgetItemID,
           a.CostSetID,
           a.ContractID,
           a.StatisticsCodeID,
           null                 as importTaxAmount,
           null                 as importTaxAmountOriginal,
           null                 as importTaxAccount,
           null                 as specialConsumeTaxAmount,
           null                 as specialConsumeTaxAmountOriginal,
           null                 as specialConsumeTaxAccount,
           a.OrderPriority,
           NULL                 as IsPromotion,
           NULL                 as InwardAmount,
           NULL                 as FromRepositoryID,
           NULL                 as ToRepositoryID,
           'MBCreditCardDetail' AS RefTable
    FROM dbo.MBCreditCardDetail a
             left join AccountingObject d on d.ID = a.AccountingObjectID
/* =======================================================================*/
    UNION ALL
    SELECT NEWID()           AS ID,
           a.ID              as RefID,
           a.MBDepositID     as RefParentID,
           a.CreditAccount,
           a.DebitAccount,
           NULL              as BankAccountDetailID,
           NULL              as BankAccount,
           NULL              as BankName,
           a.Amount,
           a.AmountOriginal,
           NULL              as VATRate,
           NULL              as VATAccount,
           NULL              as DeductionDebitAccount,
           NULL              as VATAmount,
           NULL              as VATAmountOriginal,
           NULL              as DiscountRate,
           NULL              as DiscountAccount,
           NULL              as DiscountAmount,
           NULL              as DiscountAmountOriginal,
           NULL              as ExportTaxAmount,
           NULL              as ExportTaxAmountAccount,
           NULL              as ExportTaxAccountCorresponding,
           a.Description,
           a.AccountingObjectID,
           d.AccountingObjectCode,
           d.AccountingObjectName,
           d.AccountingObjectAddress,
           NULL              as DebitAccountingObjectID,
           NULL              as DebitAccountingObjectCode,
           NULL              as DebitAccountingObjectName,
           NULL              as DebitAccountingObjectAddress,
           NULL              as CreditAccountingObjectID,
           NULL              as CreditAccountingObjectCode,
           NULL              as CreditAccountingObjectName,
           NULL              as CreditAccountingObjectAddress,
           NULL              as EmployeeID,
           NULL              as EmployeeCode,
           NULL              as EmployeeName,
           NULL              as MaterialGoodsID,
           NULL              as MaterialGoodsCode,
           NULL              as MaterialGoodsName,
           NULL              as RepositoryID,
           NULL              as RepositoryCode,
           NULL              as RepositoryName,
           NULL              as UnitID,
           NULL              as Quantity,
           NULL              as UnitPrice,
           NULL              as UnitPriceOriginal,
           NULL              as MainUnitID,
           NULL              as MainQuantity,
           NULL              as MainUnitPrice,
           NULL              as MainConvertRate,
           NULL              as Formula,
           NULL              as ConfrontID,
           NULL              as ConfrontDetailID,
           NULL              as PPOrderDetailId,
           NULL              as PPOrderDetailQuantity,
           NULL              as RepositoryAccount,
           NULL              as CostAccount,
           NULL              as vatDescription,
           NULL              as invoiceNo,
           NULL              as OWPrice,
           NULL              as OWAmount,
           NULL              as LotNo,
           NULL              as ExpiryDate,
           a.DepartmentID,
           a.ExpenseItemID,
           a.BudgetItemID,
           a.CostSetID,
           a.ContractID,
           a.StatisticsCodeID,
           null              as importTaxAmount,
           null              as importTaxAmountOriginal,
           null              as importTaxAccount,
           null              as specialConsumeTaxAmount,
           null              as specialConsumeTaxAmountOriginal,
           null              as specialConsumeTaxAccount,
           a.OrderPriority,
           NULL              as IsPromotion,
           NULL              as InwardAmount,
           NULL              as FromRepositoryID,
           NULL              as ToRepositoryID,
           'MBDepositDetail' AS RefTable
    FROM dbo.MBDepositDetail a
             left join AccountingObject d on d.ID = a.AccountingObjectID
/* =======================================================================*/
    UNION ALL
    SELECT NEWID()                    AS ID,
           a.ID                       as RefID,
           a.MBInternalTransferID     as RefParentID,
           a.CreditAccount,
           a.DebitAccount,
           NULL                       as BankAccountDetailID,
           NULL                       as BankAccount,
           NULL                       as BankName,
           a.Amount,
           a.AmountOriginal,
           NULL                       as VATRate,
           NULL                       as VATAccount,
           NULL                       as DeductionDebitAccount,
           NULL                       as VATAmount,
           NULL                       as VATAmountOriginal,
           NULL                       as DiscountRate,
           NULL                       as DiscountAccount,
           NULL                       as DiscountAmount,
           NULL                       as DiscountAmountOriginal,
           NULL                       as ExportTaxAmount,
           NULL                       as ExportTaxAmountAccount,
           NULL                       as ExportTaxAccountCorresponding,
           NULL                       as Description,
           a.AccountingObjectID,
           d.AccountingObjectCode,
           d.AccountingObjectName,
           d.AccountingObjectAddress,
           NULL                       as DebitAccountingObjectID,
           NULL                       as DebitAccountingObjectCode,
           NULL                       as DebitAccountingObjectName,
           NULL                       as DebitAccountingObjectAddress,
           NULL                       as CreditAccountingObjectID,
           NULL                       as CreditAccountingObjectCode,
           NULL                       as CreditAccountingObjectName,
           NULL                       as CreditAccountingObjectAddress,
           a.EmployeeID,
           e.AccountingObjectCode     as EmployeeCode,
           e.AccountingObjectName     as EmployeeName,
           NULL                       as MaterialGoodsID,
           NULL                       as MaterialGoodsCode,
           NULL                       as MaterialGoodsName,
           NULL                       as RepositoryID,
           NULL                       as RepositoryCode,
           NULL                       as RepositoryName,
           NULL                       as UnitID,
           NULL                       as Quantity,
           NULL                       as UnitPrice,
           NULL                       as UnitPriceOriginal,
           NULL                       as MainUnitID,
           NULL                       as MainQuantity,
           NULL                       as MainUnitPrice,
           NULL                       as MainConvertRate,
           NULL                       as Formula,
           NULL                       as ConfrontID,
           NULL                       as ConfrontDetailID,
           NULL                       as PPOrderDetailId,
           NULL                       as PPOrderDetailQuantity,
           NULL                       as RepositoryAccount,
           NULL                       as CostAccount,
           NULL                       as vatDescription,
           NULL                       as invoiceNo,
           NULL                       as OWPrice,
           NULL                       as OWAmount,
           NULL                       as LotNo,
           NULL                       as ExpiryDate,
           a.DepartmentID,
           a.ExpenseItemID,
           a.BudgetItemID,
           a.CostSetID,
           a.ContractID,
           a.StatisticsCodeID,
           null                       as importTaxAmount,
           null                       as importTaxAmountOriginal,
           null                       as importTaxAccount,
           null                       as specialConsumeTaxAmount,
           null                       as specialConsumeTaxAmountOriginal,
           null                       as specialConsumeTaxAccount,
           a.OrderPriority,
           NULL                       as IsPromotion,
           NULL                       as InwardAmount,
           NULL                       as FromRepositoryID,
           NULL                       as ToRepositoryID,
           'MBInternalTransferDetail' AS RefTable
    FROM dbo.MBInternalTransferDetail a
             left join AccountingObject d on d.ID = a.AccountingObjectID
             left join AccountingObject e on e.ID = a.EmployeeID
/* =======================================================================*/
    UNION ALL
    SELECT NEWID()                           AS ID,
           a.ID                              as RefID,
           a.PPInvoiceID                     as RefParentID,
           a.CreditAccount,
           a.DebitAccount,
           NULL                              as BankAccountDetailID,
           NULL                              as BankAccount,
           NULL                              as BankName,
           a.Amount,
           a.AmountOriginal,
           a.VATRate,
           a.VATAccount,
           a.DeductionDebitAccount,
           a.VATAmount,
           a.VATAmountOriginal,
           a.DiscountRate,
           NULL                              as DiscountAccount,
           a.DiscountAmount,
           a.DiscountAmountOriginal,
           NULL                              as ExportTaxAmount,
           NULL                              as ExportTaxAmountAccount,
           NULL                              as ExportTaxAccountCorresponding,
           a.Description,
           a.AccountingObjectID,
           d.AccountingObjectCode,
           d.AccountingObjectName,
           d.AccountingObjectAddress,
           NULL                              as DebitAccountingObjectID,
           NULL                              as DebitAccountingObjectCode,
           NULL                              as DebitAccountingObjectName,
           NULL                              as DebitAccountingObjectAddress,
           NULL                              as CreditAccountingObjectID,
           NULL                              as CreditAccountingObjectCode,
           NULL                              as CreditAccountingObjectName,
           NULL                              as CreditAccountingObjectAddress,
           NULL                              as EmployeeID,
           NULL                              as EmployeeCode,
           NULL                              as EmployeeName,
           a.MaterialGoodsID,
           m.MaterialGoodsCode,
           m.MaterialGoodsName,
           a.RepositoryID,
           r.RepositoryCode,
           r.RepositoryName,
           a.UnitID,
           a.Quantity,
           a.UnitPrice,
           a.UnitPriceOriginal,
           a.MainUnitID,
           a.MainQuantity,
           a.MainUnitPrice,
           a.MainConvertRate,
           a.Formula,
           NULL                              as ConfrontID,
           NULL                              as ConfrontDetailID,
           ppod.ID                           as PPOrderDetailId,
           ppod.QuantityReceipt              as PPOrderDetailQuantity,
           NULL                              as RepositoryAccount,
           NULL                              as CostAccount,
           a.VATDescription                  as vatDescription,
           NULL                              as invoiceNo,
           NULL                              as OWPrice,
           NULL                              as OWAmount,
           a.LotNo,
           a.ExpiryDate,
           a.DepartmentID,
           a.ExpenseItemID,
           a.BudgetItemID,
           a.CostSetID,
           a.ContractID,
           a.StatisticCodeID                 as StatisticsCodeID,
           a.ImportTaxAmount                 as importTaxAmount,
           a.ImportTaxAmountOriginal         as importTaxAmountOriginal,
           a.ImportTaxAccount                as importTaxAccount,
           a.SpecialConsumeTaxAmount         as specialConsumeTaxAmount,
           a.SpecialConsumeTaxAmountOriginal as specialConsumeTaxAmountOriginal,
           a.SpecialConsumeTaxAccount        as specialConsumeTaxAccount,
           a.OrderPriority,
           NULL                              as IsPromotion,
           a.InwardAmount                    as InwardAmount,
           NULL                              as FromRepositoryID,
           NULL                              as ToRepositoryID,
           'PPInvoiceDetail'                 AS RefTable
    FROM dbo.PPInvoiceDetail a
             left join AccountingObject d on d.ID = a.AccountingObjectID
             left join MaterialGoods m on m.ID = a.MaterialGoodsID
             left join Repository r on r.ID = a.RepositoryID
             left join PPOrderDetail ppod on ppod.id = a.PPOrderDetailID
/* =======================================================================*/
    UNION ALL
    SELECT NEWID()              AS ID,
           a.ID                 as RefID,
           a.PPServiceID        as RefParentID,
           a.CreditAccount,
           a.DebitAccount,
           NULL                 as BankAccountDetailID,
           NULL                 as BankAccount,
           NULL                 as BankName,
           a.Amount,
           a.AmountOriginal,
           a.VATRate,
           a.VATAccount,
           a.DeductionDebitAccount,
           a.VATAmount,
           a.VATAmountOriginal,
           a.DiscountRate,
           a.DiscountAccount,
           a.DiscountAmount,
           a.DiscountAmountOriginal,
           NULL                 as ExportTaxAmount,
           NULL                 as ExportTaxAmountAccount,
           NULL                 as ExportTaxAccountCorresponding,
           a.Description,
           a.AccountingObjectID,
           d.AccountingObjectCode,
           d.AccountingObjectName,
           d.AccountingObjectAddress,
           NULL                 as DebitAccountingObjectID,
           NULL                 as DebitAccountingObjectCode,
           NULL                 as DebitAccountingObjectName,
           NULL                 as DebitAccountingObjectAddress,
           NULL                 as CreditAccountingObjectID,
           NULL                 as CreditAccountingObjectCode,
           NULL                 as CreditAccountingObjectName,
           NULL                 as CreditAccountingObjectAddress,
           NULL                 as EmployeeID,
           NULL                 as EmployeeCode,
           NULL                 as EmployeeName,
           a.MaterialGoodsID,
           m.MaterialGoodsCode,
           m.MaterialGoodsName,
           NULL                 as RepositoryID,
           NULL                 as RepositoryCode,
           NULL                 as RepositoryName,
           a.UnitID,
           a.Quantity,
           a.UnitPrice,
           a.UnitPriceOriginal,
           NULL                 as MainUnitID,
           NULL                 as MainQuantity,
           NULL                 as MainUnitPrice,
           NULL                 as MainConvertRate,
           NULL                 as Formula,
           NULL                 as ConfrontID,
           NULL                 as ConfrontDetailID,
           ppod.ID              as PPOrderDetailId,
           ppod.QuantityReceipt as PPOrderDetailQuantity,
           NULL                 as RepositoryAccount,
           NULL                 as CostAccount,
           a.VATDescription     as vatDescription,
           ppo.No               as invoiceNo,
           NULL                 as OWPrice,
           NULL                 as OWAmount,
           NULL                 as LotNo,
           NULL                 as ExpiryDate,
           a.DepartmentID,
           a.ExpenseItemID,
           a.BudgetItemID,
           a.CostSetID,
           a.ContractID,
           a.StatisticsCodeID,
           null                 as importTaxAmount,
           null                 as importTaxAmountOriginal,
           null                 as importTaxAccount,
           null                 as specialConsumeTaxAmount,
           null                 as specialConsumeTaxAmountOriginal,
           null                 as specialConsumeTaxAccount,
           a.OrderPriority,
           NULL                 as IsPromotion,
           NULL                 as InwardAmount,
           NULL                 as FromRepositoryID,
           NULL                 as ToRepositoryID,
           'PPServiceDetail'    AS RefTable
    FROM dbo.PPServiceDetail a
             left join AccountingObject d on d.ID = a.AccountingObjectID
             left join MaterialGoods m on m.ID = a.MaterialGoodsID
             left join PPOrder ppo on ppo.id = a.PPOrderID
             left join PPOrderDetail ppod on ppod.id = a.PPOrderDetailID
/* =======================================================================*/
    UNION ALL
    SELECT NEWID()                  AS ID,
           a.ID                     as RefID,
           a.PPDiscountReturnID     as RefParentID,
           a.CreditAccount,
           a.DebitAccount,
           NULL                     as BankAccountDetailID,
           NULL                     as BankAccount,
           NULL                     as BankName,
           a.Amount,
           a.AmountOriginal,
           a.VATRate,
           a.VATAccount,
           a.DeductionDebitAccount,
           a.VATAmount,
           a.VATAmountOriginal,
           NULL                     as DiscountRate,
           NULL                     as DiscountAccount,
           NULL                     as DiscountAmount,
           NULL                     as DiscountAmountOriginal,
           NULL                     as ExportTaxAmount,
           NULL                     as ExportTaxAmountAccount,
           NULL                     as ExportTaxAccountCorresponding,
           a.Description,
           a.AccountingObjectID,
           d.AccountingObjectCode,
           d.AccountingObjectName,
           d.AccountingObjectAddress,
           NULL                     as DebitAccountingObjectID,
           NULL                     as DebitAccountingObjectCode,
           NULL                     as DebitAccountingObjectName,
           NULL                     as DebitAccountingObjectAddress,
           NULL                     as CreditAccountingObjectID,
           NULL                     as CreditAccountingObjectCode,
           NULL                     as CreditAccountingObjectName,
           NULL                     as CreditAccountingObjectAddress,
           NULL                     as EmployeeID,
           NULL                     as EmployeeCode,
           NULL                     as EmployeeName,
           a.MaterialGoodsID,
           m.MaterialGoodsCode,
           m.MaterialGoodsName,
           a.RepositoryID,
           r.RepositoryCode,
           r.RepositoryName,
           a.UnitID,
           a.Quantity,
           a.UnitPrice,
           a.UnitPriceOriginal,
           a.MainUnitID,
           a.MainQuantity,
           a.MainUnitPrice,
           a.MainConvertRate,
           a.Formula,
           NULL                     as ConfrontID,
           NULL                     as ConfrontDetailID,
           NULL                     as PPOrderDetailId,
           NULL                     as PPOrderDetailQuantity,
           NULL                     as RepositoryAccount,
           NULL                     as CostAccount,
           a.VATDescription         as VATDescription,
           NULL                     as invoiceNo,
           NULL                     as OWPrice,
           NULL                     as OWAmount,
           a.LotNo,
           a.ExpiryDate,
           a.DepartmentID,
           a.ExpenseItemID,
           a.BudgetItemID,
           a.CostSetID,
           a.ContractID,
           a.StatisticsCodeID,
           null                     as importTaxAmount,
           null                     as importTaxAmountOriginal,
           null                     as importTaxAccount,
           null                     as specialConsumeTaxAmount,
           null                     as specialConsumeTaxAmountOriginal,
           null                     as specialConsumeTaxAccount,
           a.OrderPriority,
           a.IsPromotion            as IsPromotion,
           NULL                     as InwardAmount,
           NULL                     as FromRepositoryID,
           NULL                     as ToRepositoryID,
           'PPDiscountReturnDetail' AS RefTable
    FROM dbo.PPDiscountReturnDetail a
             left join AccountingObject d on d.ID = a.AccountingObjectID
             left join MaterialGoods m on m.ID = a.MaterialGoodsID
             left join Repository r on r.ID = a.RepositoryID
/* =======================================================================*/
    UNION ALL
    SELECT NEWID()           AS ID,
           a.ID              as RefID,
           a.SAInvoiceID     as RefParentID,
           a.CreditAccount,
           a.DebitAccount,
           NULL              as BankAccountDetailID,
           NULL              as BankAccount,
           NULL              as BankName,
           a.Amount,
           a.AmountOriginal,
           a.VATRate,
           a.VATAccount,
           a.DeductionDebitAccount,
           a.VATAmount,
           a.VATAmountOriginal,
           a.DiscountRate,
           a.DiscountAccount,
           a.DiscountAmount,
           a.DiscountAmountOriginal,
           a.ExportTaxAmount,
           a.ExportTaxAmountAccount,
           a.ExportTaxAccountCorresponding,
           a.Description,
           a.AccountingObjectID,
           d.AccountingObjectCode,
           d.AccountingObjectName,
           d.AccountingObjectAddress,
           NULL              as DebitAccountingObjectID,
           NULL              as DebitAccountingObjectCode,
           NULL              as DebitAccountingObjectName,
           NULL              as DebitAccountingObjectAddress,
           NULL              as CreditAccountingObjectID,
           NULL              as CreditAccountingObjectCode,
           NULL              as CreditAccountingObjectName,
           NULL              as CreditAccountingObjectAddress,
           NULL              as EmployeeID,
           NULL              as EmployeeCode,
           NULL              as EmployeeName,
           a.MaterialGoodsID,
           m.MaterialGoodsCode,
           m.MaterialGoodsName,
           a.RepositoryID,
           r.RepositoryCode,
           r.RepositoryName,
           a.UnitID,
           a.Quantity,
           a.UnitPrice,
           a.UnitPriceOriginal,
           a.MainUnitID,
           a.MainQuantity,
           a.MainUnitPrice,
           a.MainConvertRate,
           a.Formula,
           a.ConfrontID,
           a.ConfrontDetailID,
           NULL              as PPOrderDetailId,
           NULL              as PPOrderDetailQuantity,
           a.RepositoryAccount,
           a.CostAccount,
           a.VATDescription  as vatDescription,
           NULL              as invoiceNo,
           a.OWPrice,
           a.OWAmount,
           a.LotNo,
           a.ExpiryDate,
           a.DepartmentID,
           a.ExpenseItemID,
           a.BudgetItemID,
           a.CostSetID,
           a.ContractID,
           a.StatisticsCodeID,
           null              as importTaxAmount,
           null              as importTaxAmountOriginal,
           null              as importTaxAccount,
           null              as specialConsumeTaxAmount,
           null              as specialConsumeTaxAmountOriginal,
           null              as specialConsumeTaxAccount,
           a.OrderPriority,
           a.IsPromotion     as IsPromotion,
           NULL              as InwardAmount,
           NULL              as FromRepositoryID,
           NULL              as ToRepositoryID,
           'SAInvoiceDetail' AS RefTable
    FROM dbo.SAInvoiceDetail a
             left join AccountingObject d on d.ID = a.AccountingObjectID
             left join MaterialGoods m on m.ID = a.MaterialGoodsID
             left join Repository r on r.ID = a.RepositoryID
/* =======================================================================*/
    UNION ALL
    SELECT NEWID()          AS ID,
           a.ID             as RefID,
           a.SAReturnID     as RefParentID,
           a.CreditAccount,
           a.DebitAccount,
           NULL             as BankAccountDetailID,
           NULL             as BankAccount,
           NULL             as BankName,
           a.Amount,
           a.AmountOriginal,
           a.VATRate,
           a.VATAccount,
           a.DeductionDebitAccount,
           a.VATAmount,
           a.VATAmountOriginal,
           a.DiscountRate,
           a.DiscountAccount,
           a.DiscountAmount,
           a.DiscountAmountOriginal,
           NULL             as ExportTaxAmount,
           NULL             as ExportTaxAmountAccount,
           NULL             as ExportTaxAccountCorresponding,
           a.Description,
           a.AccountingObjectID,
           d.AccountingObjectCode,
           d.AccountingObjectName,
           d.AccountingObjectAddress,
           NULL             as DebitAccountingObjectID,
           NULL             as DebitAccountingObjectCode,
           NULL             as DebitAccountingObjectName,
           NULL             as DebitAccountingObjectAddress,
           NULL             as CreditAccountingObjectID,
           NULL             as CreditAccountingObjectCode,
           NULL             as CreditAccountingObjectName,
           NULL             as CreditAccountingObjectAddress,
           NULL             as EmployeeID,
           NULL             as EmployeeCode,
           NULL             as EmployeeName,
           a.MaterialGoodsID,
           m.MaterialGoodsCode,
           m.MaterialGoodsName,
           a.RepositoryID,
           r.RepositoryCode,
           r.RepositoryName,
           a.UnitID,
           a.Quantity,
           a.UnitPrice,
           a.UnitPriceOriginal,
           a.MainUnitID,
           a.MainQuantity,
           a.MainUnitPrice,
           a.MainConvertRate,
           a.Formula,
           NULL             as ConfrontID,
           NULL             as ConfrontDetailID,
           NULL             as PPOrderDetailId,
           NULL             as PPOrderDetailQuantity,
           a.RepositoryAccount,
           a.CostAccount,
           a.VATDescription as vatDescription,
           NULL             as invoiceNo,
           a.OWPrice,
           a.OWAmount,
           a.LotNo,
           a.ExpiryDate,
           a.DepartmentID,
           a.ExpenseItemID,
           a.BudgetItemID,
           a.CostSetID,
           a.ContractID,
           a.StatisticsCodeID,
           null             as importTaxAmount,
           null             as importTaxAmountOriginal,
           null             as importTaxAccount,
           null             as specialConsumeTaxAmount,
           null             as specialConsumeTaxAmountOriginal,
           null             as specialConsumeTaxAccount,
           a.OrderPriority,
           a.IsPromotion    as IsPromotion,
           NULL             as InwardAmount,
           NULL             as FromRepositoryID,
           NULL             as ToRepositoryID,
           'SAReturnDetail' AS RefTable
    FROM dbo.SAReturnDetail a
             left join AccountingObject d on d.ID = a.AccountingObjectID
             left join MaterialGoods m on m.ID = a.MaterialGoodsID
             left join Repository r on r.ID = a.RepositoryID
/* =======================================================================*/
    UNION ALL
    SELECT NEWID()                 AS ID,
           a.ID                    as RefID,
           a.RSInwardOutwardID     as RefParentID,
           a.CreditAccount,
           a.DebitAccount,
           NULL                    as BankAccountDetailID,
           NULL                    as BankAccount,
           NULL                    as BankName,
           a.Amount,
           a.AmountOriginal,
           NULL                    as VATRate,
           NULL                    as VATAccount,
           NULL                    as DeductionDebitAccount,
           NULL                    as VATAmount,
           NULL                    as VATAmountOriginal,
           NULL                    as DiscountRate,
           NULL                    as DiscountAccount,
           NULL                    as DiscountAmount,
           NULL                    as DiscountAmountOriginal,
           NULL                    as ExportTaxAmount,
           NULL                    as ExportTaxAmountAccount,
           NULL                    as ExportTaxAccountCorresponding,
           a.Description,
           NULL                    as AccountingObjectID,
           NULL                    as AccountingObjectCode,
           NULL                    as AccountingObjectName,
           NULL                    as AccountingObjectAddress,
           NULL                    as DebitAccountingObjectID,
           NULL                    as DebitAccountingObjectCode,
           NULL                    as DebitAccountingObjectName,
           NULL                    as DebitAccountingObjectAddress,
           NULL                    as CreditAccountingObjectID,
           NULL                    as CreditAccountingObjectCode,
           NULL                    as CreditAccountingObjectName,
           NULL                    as CreditAccountingObjectAddress,
           a.EmployeeID,
           e.AccountingObjectCode  as EmployeeCode,
           e.AccountingObjectName  as EmployeeName,
           a.MaterialGoodsID,
           m.MaterialGoodsCode,
           m.MaterialGoodsName,
           a.RepositoryID,
           r.RepositoryCode,
           r.RepositoryName,
           a.UnitID,
           a.Quantity,
           a.UnitPrice,
           a.UnitPriceOriginal,
           a.MainUnitID,
           a.MainQuantity,
           a.MainUnitPrice,
           a.MainConvertRate,
           a.Formula,
           a.ConfrontID,
           a.ConfrontDetailID,
           ppod.ID                 as PPOrderDetailId,
           ppod.QuantityReceipt    as PPOrderDetailQuantity,
           NULL                    as RepositoryAccount,
           NULL                    as CostAccount,
           NULL                    as vatDescription,
           NULL                    as invoiceNo,
           NULL                    as OWPrice,
           NULL                    as OWAmount,
           a.LotNo,
           a.ExpiryDate,
           a.DepartmentID,
           a.ExpenseItemID,
           a.BudgetItemID,
           a.CostSetID,
           a.ContractID,
           a.StatisticsCodeID,
           null                    as importTaxAmount,
           null                    as importTaxAmountOriginal,
           null                    as importTaxAccount,
           null                    as specialConsumeTaxAmount,
           null                    as specialConsumeTaxAmountOriginal,
           null                    as specialConsumeTaxAccount,
           a.OrderPriority,
           NULL                    as IsPromotion,
           NULL                    as InwardAmount,
           NULL                    as FromRepositoryID,
           NULL                    as ToRepositoryID,
           'RSInwardOutwardDetail' AS RefTable
    FROM dbo.RSInwardOutwardDetail a
             left join AccountingObject e on e.ID = a.EmployeeID
             left join MaterialGoods m on m.ID = a.MaterialGoodsID
             left join Repository r on r.ID = a.RepositoryID
             left join PPOrderDetail ppod on ppod.id = a.PPOrderDetailsID
/* =======================================================================*/
    UNION ALL
    SELECT NEWID()            AS ID,
           a.ID               as RefID,
           a.RSTransferID     as RefParentID,
           a.CreditAccount,
           a.DebitAccount,
           NULL               as BankAccountDetailID,
           NULL               as BankAccount,
           NULL               as BankName,
           a.Amount,
           a.AmountOriginal,
           NULL               as VATRate,
           NULL               as VATAccount,
           NULL               as DeductionDebitAccount,
           NULL               as VATAmount,
           NULL               as VATAmountOriginal,
           NULL               as DiscountRate,
           NULL               as DiscountAccount,
           NULL               as DiscountAmount,
           NULL               as DiscountAmountOriginal,
           NULL               as ExportTaxAmount,
           NULL               as ExportTaxAmountAccount,
           NULL               as ExportTaxAccountCorresponding,
           a.Description,
           NULL               as AccountingObjectID,
           NULL               as AccountingObjectCode,
           NULL               as AccountingObjectName,
           NULL               as AccountingObjectAddress,
           NULL               as DebitAccountingObjectID,
           NULL               as DebitAccountingObjectCode,
           NULL               as DebitAccountingObjectName,
           NULL               as DebitAccountingObjectAddress,
           NULL               as CreditAccountingObjectID,
           NULL               as CreditAccountingObjectCode,
           NULL               as CreditAccountingObjectName,
           NULL               as CreditAccountingObjectAddress,
           NULL               as EmployeeID,
           NULL               as EmployeeCode,
           NULL               as EmployeeName,
           a.MaterialGoodsID,
           m.MaterialGoodsCode,
           m.MaterialGoodsName,
           NULL               as RepositoryID,
           NULL               as RepositoryCode,
           NULL               as RepositoryName,
           a.UnitID,
           a.Quantity,
           a.UnitPrice,
           a.UnitPriceOriginal,
           a.MainUnitID,
           a.MainQuantity,
           a.MainUnitPrice,
           a.MainConvertRate,
           a.Formula,
           a.ConfrontID,
           a.ConfrontDetailID,
           NULL               as PPOrderDetailId,
           NULL               as PPOrderDetailQuantity,
           NULL               as RepositoryAccount,
           NULL               as CostAccount,
           NULL               as vatDescription,
           NULL               as invoiceNo,
           a.OWPrice,
           a.OWAmount,
           a.LotNo,
           a.ExpiryDate,
           a.DepartmentID,
           a.ExpenseItemID,
           a.BudgetItemID,
           a.CostSetID,
           NULL               as ContractID,
           a.StatisticsCodeID,
           null               as importTaxAmount,
           null               as importTaxAmountOriginal,
           null               as importTaxAccount,
           null               as specialConsumeTaxAmount,
           null               as specialConsumeTaxAmountOriginal,
           null               as specialConsumeTaxAccount,
           a.OrderPriority,
           NULL               as IsPromotion,
           NULL               as InwardAmount,
           a.FromRepositoryID,
           a.ToRepositoryID,
           'RSTransferDetail' AS RefTable
    FROM dbo.RSTransferDetail a
             left join MaterialGoods m on m.ID = a.MaterialGoodsID
/* =======================================================================*/
    UNION ALL
    SELECT NEWID()             AS ID,
           a.ID                as RefID,
           a.TIIncrementID     as RefParentID,
           NULL                as CreditAccount,
           NULL                as DebitAccount,
           NULL                as BankAccountDetailID,
           NULL                as BankAccount,
           NULL                as BankName,
           a.Amount,
           NULL                as AmountOriginal,
           NULL                as VATRate,
           NULL                as VATAccount,
           NULL                as DeductionDebitAccount,
           NULL                as VATAmount,
           NULL                as VATAmountOriginal,
           NULL                as DiscountRate,
           NULL                as DiscountAccount,
           NULL                as DiscountAmount,
           NULL                as DiscountAmountOriginal,
           NULL                as ExportTaxAmount,
           NULL                as ExportTaxAmountAccount,
           NULL                as ExportTaxAccountCorresponding,
           a.Description,
           a.AccountingObjectID,
           d.AccountingObjectCode,
           d.AccountingObjectName,
           d.AccountingObjectAddress,
           NULL                as DebitAccountingObjectID,
           NULL                as DebitAccountingObjectCode,
           NULL                as DebitAccountingObjectName,
           NULL                as DebitAccountingObjectAddress,
           NULL                as CreditAccountingObjectID,
           NULL                as CreditAccountingObjectCode,
           NULL                as CreditAccountingObjectName,
           NULL                as CreditAccountingObjectAddress,
           NULL                as EmployeeID,
           NULL                as EmployeeCode,
           NULL                as EmployeeName,
           NULL                as MaterialGoodsID,
           NULL                as MaterialGoodsCode,
           NULL                as MaterialGoodsName,
           NULL                as RepositoryID,
           NULL                as RepositoryCode,
           NULL                as RepositoryName,
           a.UnitID,
           a.Quantity,
           a.UnitPrice,
           NULL                as UnitPriceOriginal,
           NULL                as MainUnitID,
           NULL                as MainQuantity,
           NULL                as MainUnitPrice,
           NULL                as MainConvertRate,
           NULL                as Formula,
           NULL                as ConfrontID,
           NULL                as ConfrontDetailID,
           NULL                as PPOrderDetailId,
           NULL                as PPOrderDetailQuantity,
           NULL                as RepositoryAccount,
           NULL                as CostAccount,
           NULL                as vatDescription,
           NULL                as invoiceNo,
           NULL                as OWPrice,
           NULL                as OWAmount,
           NULL                as LotNo,
           NULL                as ExpiryDate,
           a.DepartmentID,
           a.ExpenseItemID,
           a.BudgetItemID,
           a.CostSetID,
           a.ContractID,
           NULL                as StatisticsCodeID,
           null                as importTaxAmount,
           null                as importTaxAmountOriginal,
           null                as importTaxAccount,
           null                as specialConsumeTaxAmount,
           null                as specialConsumeTaxAmountOriginal,
           null                as specialConsumeTaxAccount,
           a.OrderPriority,
           NULL                as IsPromotion,
           NULL                as InwardAmount,
           NULL                as FromRepositoryID,
           NULL                as ToRepositoryID,
           'TIIncrementDetail' AS RefTable
    FROM dbo.TIIncrementDetail a
             left join AccountingObject d on d.ID = a.AccountingObjectID
/* =======================================================================*/
    UNION ALL
    SELECT NEWID()             AS ID,
           a.ID                as RefID,
           a.TIDecrementID     as RefParentID,
           NULL                as CreditAccount,
           NULL                as DebitAccount,
           NULL                as BankAccountDetailID,
           NULL                as BankAccount,
           NULL                as BankName,
           a.Amount,
           NULL                as AmountOriginal,
           NULL                as VATRate,
           NULL                as VATAccount,
           NULL                as DeductionDebitAccount,
           NULL                as VATAmount,
           NULL                as VATAmountOriginal,
           NULL                as DiscountRate,
           NULL                as DiscountAccount,
           NULL                as DiscountAmount,
           NULL                as DiscountAmountOriginal,
           NULL                as ExportTaxAmount,
           NULL                as ExportTaxAmountAccount,
           NULL                as ExportTaxAccountCorresponding,
           a.Description,
           NULL                as AccountingObjectID,
           NULL                as AccountingObjectCode,
           NULL                as AccountingObjectName,
           NULL                as AccountingObjectAddress,
           NULL                as DebitAccountingObjectID,
           NULL                as DebitAccountingObjectCode,
           NULL                as DebitAccountingObjectName,
           NULL                as DebitAccountingObjectAddress,
           NULL                as CreditAccountingObjectID,
           NULL                as CreditAccountingObjectCode,
           NULL                as CreditAccountingObjectName,
           NULL                as CreditAccountingObjectAddress,
           NULL                as EmployeeID,
           NULL                as EmployeeCode,
           NULL                as EmployeeName,
           NULL                as MaterialGoodsID,
           NULL                as MaterialGoodsCode,
           NULL                as MaterialGoodsName,
           NULL                as RepositoryID,
           NULL                as RepositoryCode,
           NULL                as RepositoryName,
           NULL                as UnitID,
           a.Quantity,
           NULL                as UnitPrice,
           NULL                as UnitPriceOriginal,
           NULL                as MainUnitID,
           NULL                as MainQuantity,
           NULL                as MainUnitPrice,
           NULL                as MainConvertRate,
           NULL                as Formula,
           NULL                as ConfrontID,
           NULL                as ConfrontDetailID,
           NULL                as PPOrderDetailId,
           NULL                as PPOrderDetailQuantity,
           NULL                as RepositoryAccount,
           NULL                as CostAccount,
           NULL                as vatDescription,
           NULL                as invoiceNo,
           NULL                as OWPrice,
           NULL                as OWAmount,
           NULL                as LotNo,
           NULL                as ExpiryDate,
           a.DepartmentID,
           NULL                as ExpenseItemID,
           NULL                as BudgetItemID,
           NULL                as CostSetID,
           NULL                as ContractID,
           NULL                as StatisticsCodeID,
           null                as importTaxAmount,
           null                as importTaxAmountOriginal,
           null                as importTaxAccount,
           null                as specialConsumeTaxAmount,
           null                as specialConsumeTaxAmountOriginal,
           null                as specialConsumeTaxAccount,
           a.OrderPriority,
           NULL                as IsPromotion,
           NULL                as InwardAmount,
           NULL                as FromRepositoryID,
           NULL                as ToRepositoryID,
           'TIDecrementDetail' AS RefTable
    FROM dbo.TIDecrementDetail a
/* =======================================================================*/
    UNION ALL
    SELECT NEWID()              AS ID,
           a.ID                 as RefID,
           a.TIAdjustmentID     as RefParentID,
           NULL                 as CreditAccount,
           NULL                 as DebitAccount,
           NULL                 as BankAccountDetailID,
           NULL                 as BankAccount,
           NULL                 as BankName,
           NULL                 as Amount,
           NULL                 as AmountOriginal,
           NULL                 as VATRate,
           NULL                 as VATAccount,
           NULL                 as DeductionDebitAccount,
           NULL                 as VATAmount,
           NULL                 as VATAmountOriginal,
           NULL                 as DiscountRate,
           NULL                 as DiscountAccount,
           NULL                 as DiscountAmount,
           NULL                 as DiscountAmountOriginal,
           NULL                 as ExportTaxAmount,
           NULL                 as ExportTaxAmountAccount,
           NULL                 as ExportTaxAccountCorresponding,
           a.Description,
           NULL                 as AccountingObjectID,
           NULL                 as AccountingObjectCode,
           NULL                 as AccountingObjectName,
           NULL                 as AccountingObjectAddress,
           NULL                 as DebitAccountingObjectID,
           NULL                 as DebitAccountingObjectCode,
           NULL                 as DebitAccountingObjectName,
           NULL                 as DebitAccountingObjectAddress,
           NULL                 as CreditAccountingObjectID,
           NULL                 as CreditAccountingObjectCode,
           NULL                 as CreditAccountingObjectName,
           NULL                 as CreditAccountingObjectAddress,
           NULL                 as EmployeeID,
           NULL                 as EmployeeCode,
           NULL                 as EmployeeName,
           NULL                 as MaterialGoodsID,
           NULL                 as MaterialGoodsCode,
           NULL                 as MaterialGoodsName,
           NULL                 as RepositoryID,
           NULL                 as RepositoryCode,
           NULL                 as RepositoryName,
           NULL                 as UnitID,
           a.Quantity,
           NULL                 as UnitPrice,
           NULL                 as UnitPriceOriginal,
           NULL                 as MainUnitID,
           NULL                 as MainQuantity,
           NULL                 as MainUnitPrice,
           NULL                 as MainConvertRate,
           NULL                 as Formula,
           NULL                 as ConfrontID,
           NULL                 as ConfrontDetailID,
           NULL                 as PPOrderDetailId,
           NULL                 as PPOrderDetailQuantity,
           NULL                 as RepositoryAccount,
           NULL                 as CostAccount,
           NULL                 as vatDescription,
           NULL                 as invoiceNo,
           NULL                 as OWPrice,
           NULL                 as OWAmount,
           NULL                 as LotNo,
           NULL                 as ExpiryDate,
           NULL                 as DepartmentID,
           NULL                 as ExpenseItemID,
           NULL                 as BudgetItemID,
           NULL                 as CostSetID,
           NULL                 as ContractID,
           NULL                 as StatisticsCodeID,
           null                 as importTaxAmount,
           null                 as importTaxAmountOriginal,
           null                 as importTaxAccount,
           null                 as specialConsumeTaxAmount,
           null                 as specialConsumeTaxAmountOriginal,
           null                 as specialConsumeTaxAccount,
           a.OrderPriority,
           NULL                 as IsPromotion,
           NULL                 as InwardAmount,
           NULL                 as FromRepositoryID,
           NULL                 as ToRepositoryID,
           'TIAdjustmentDetail' AS RefTable
    FROM dbo.TIAdjustmentDetail a
/* =======================================================================*/
    UNION ALL
    SELECT NEWID()            AS ID,
           a.ID               as RefID,
           a.TITransferID     as RefParentID,
           NULL               as CreditAccount,
           NULL               as DebitAccount,
           NULL               as BankAccountDetailID,
           NULL               as BankAccount,
           NULL               as BankName,
           NULL               as Amount,
           NULL               as AmountOriginal,
           NULL               as VATRate,
           NULL               as VATAccount,
           NULL               as DeductionDebitAccount,
           NULL               as VATAmount,
           NULL               as VATAmountOriginal,
           NULL               as DiscountRate,
           NULL               as DiscountAccount,
           NULL               as DiscountAmount,
           NULL               as DiscountAmountOriginal,
           NULL               as ExportTaxAmount,
           NULL               as ExportTaxAmountAccount,
           NULL               as ExportTaxAccountCorresponding,
           a.Description,
           NULL               as AccountingObjectID,
           NULL               as AccountingObjectCode,
           NULL               as AccountingObjectName,
           NULL               as AccountingObjectAddress,
           NULL               as DebitAccountingObjectID,
           NULL               as DebitAccountingObjectCode,
           NULL               as DebitAccountingObjectName,
           NULL               as DebitAccountingObjectAddress,
           NULL               as CreditAccountingObjectID,
           NULL               as CreditAccountingObjectCode,
           NULL               as CreditAccountingObjectName,
           NULL               as CreditAccountingObjectAddress,
           NULL               as EmployeeID,
           NULL               as EmployeeCode,
           NULL               as EmployeeName,
           NULL               as MaterialGoodsID,
           NULL               as MaterialGoodsCode,
           NULL               as MaterialGoodsName,
           NULL               as RepositoryID,
           NULL               as RepositoryCode,
           NULL               as RepositoryName,
           NULL               as UnitID,
           a.Quantity,
           NULL               as UnitPrice,
           NULL               as UnitPriceOriginal,
           NULL               as MainUnitID,
           NULL               as MainQuantity,
           NULL               as MainUnitPrice,
           NULL               as MainConvertRate,
           NULL               as Formula,
           NULL               as ConfrontID,
           NULL               as ConfrontDetailID,
           NULL               as PPOrderDetailId,
           NULL               as PPOrderDetailQuantity,
           NULL               as RepositoryAccount,
           a.CostAccount,
           NULL               as vatDescription,
           NULL               as invoiceNo,
           NULL               as OWPrice,
           NULL               as OWAmount,
           NULL               as LotNo,
           NULL               as ExpiryDate,
           NULL               as DepartmentID,
           a.ExpenseItemID,
           a.BudgetItemID,
           a.CostSetID,
           NULL               as ContractID,
           NULL               as StatisticsCodeID,
           null               as importTaxAmount,
           null               as importTaxAmountOriginal,
           null               as importTaxAccount,
           null               as specialConsumeTaxAmount,
           null               as specialConsumeTaxAmountOriginal,
           null               as specialConsumeTaxAccount,
           a.OrderPriority,
           NULL               as IsPromotion,
           NULL               as InwardAmount,
           NULL               as FromRepositoryID,
           NULL               as ToRepositoryID,
           'TITransferDetail' AS RefTable
    FROM dbo.TITransferDetail a
/* =======================================================================*/
    UNION ALL
    SELECT NEWID()              AS ID,
           a.ID                 as RefID,
           a.TIAllocationID     as RefParentID,
           NULL                 as CreditAccount,
           NULL                 as DebitAccount,
           NULL                 as BankAccountDetailID,
           NULL                 as BankAccount,
           NULL                 as BankName,
           NULL                 as Amount,
           NULL                 as AmountOriginal,
           NULL                 as VATRate,
           NULL                 as VATAccount,
           NULL                 as DeductionDebitAccount,
           NULL                 as VATAmount,
           NULL                 as VATAmountOriginal,
           NULL                 as DiscountRate,
           NULL                 as DiscountAccount,
           NULL                 as DiscountAmount,
           NULL                 as DiscountAmountOriginal,
           NULL                 as ExportTaxAmount,
           NULL                 as ExportTaxAmountAccount,
           NULL                 as ExportTaxAccountCorresponding,
           a.Description,
           NULL                 as AccountingObjectID,
           NULL                 as AccountingObjectCode,
           NULL                 as AccountingObjectName,
           NULL                 as AccountingObjectAddress,
           NULL                 as DebitAccountingObjectID,
           NULL                 as DebitAccountingObjectCode,
           NULL                 as DebitAccountingObjectName,
           NULL                 as DebitAccountingObjectAddress,
           NULL                 as CreditAccountingObjectID,
           NULL                 as CreditAccountingObjectCode,
           NULL                 as CreditAccountingObjectName,
           NULL                 as CreditAccountingObjectAddress,
           NULL                 as EmployeeID,
           NULL                 as EmployeeCode,
           NULL                 as EmployeeName,
           NULL                 as MaterialGoodsID,
           NULL                 as MaterialGoodsCode,
           NULL                 as MaterialGoodsName,
           NULL                 as RepositoryID,
           NULL                 as RepositoryCode,
           NULL                 as RepositoryName,
           NULL                 as UnitID,
           NULL                 as Quantity,
           NULL                 as UnitPrice,
           NULL                 as UnitPriceOriginal,
           NULL                 as MainUnitID,
           NULL                 as MainQuantity,
           NULL                 as MainUnitPrice,
           NULL                 as MainConvertRate,
           NULL                 as Formula,
           NULL                 as ConfrontID,
           NULL                 as ConfrontDetailID,
           NULL                 as PPOrderDetailId,
           NULL                 as PPOrderDetailQuantity,
           NULL                 as RepositoryAccount,
           NULL                 as CostAccount,
           NULL                 as vatDescription,
           NULL                 as invoiceNo,
           NULL                 as OWPrice,
           NULL                 as OWAmount,
           NULL                 as LotNo,
           NULL                 as ExpiryDate,
           NULL                 as DepartmentID,
           NULL                 as ExpenseItemID,
           NULL                 as BudgetItemID,
           NULL                 as CostSetID,
           NULL                 as ContractID,
           NULL                 as StatisticsCodeID,
           null                 as importTaxAmount,
           null                 as importTaxAmountOriginal,
           null                 as importTaxAccount,
           null                 as specialConsumeTaxAmount,
           null                 as specialConsumeTaxAmountOriginal,
           null                 as specialConsumeTaxAccount,
           a.OrderPriority,
           NULL                 as IsPromotion,
           NULL                 as InwardAmount,
           NULL                 as FromRepositoryID,
           NULL                 as ToRepositoryID,
           'TIAllocationDetail' AS RefTable
    FROM dbo.TIAllocationDetail a
/* =======================================================================*/
    UNION ALL
    SELECT NEWID()             AS ID,
           a.ID                as RefID,
           a.FAIncrementID     as RefParentID,
           NULL                as CreditAccount,
           NULL                as DebitAccount,
           NULL                as BankAccountDetailID,
           NULL                as BankAccount,
           NULL                as BankName,
           a.Amount,
           NULL                as AmountOriginal,
           NULL                as VATRate,
           NULL                as VATAccount,
           NULL                as DeductionDebitAccount,
           NULL                as VATAmount,
           NULL                as VATAmountOriginal,
           NULL                as DiscountRate,
           NULL                as DiscountAccount,
           NULL                as DiscountAmount,
           NULL                as DiscountAmountOriginal,
           NULL                as ExportTaxAmount,
           NULL                as ExportTaxAmountAccount,
           NULL                as ExportTaxAccountCorresponding,
           a.Description,
           a.AccountingObjectID,
           d.AccountingObjectCode,
           d.AccountingObjectName,
           d.AccountingObjectAddress,
           NULL                as DebitAccountingObjectID,
           NULL                as DebitAccountingObjectCode,
           NULL                as DebitAccountingObjectName,
           NULL                as DebitAccountingObjectAddress,
           NULL                as CreditAccountingObjectID,
           NULL                as CreditAccountingObjectCode,
           NULL                as CreditAccountingObjectName,
           NULL                as CreditAccountingObjectAddress,
           NULL                as EmployeeID,
           NULL                as EmployeeCode,
           NULL                as EmployeeName,
           NULL                as MaterialGoodsID,
           NULL                as MaterialGoodsCode,
           NULL                as MaterialGoodsName,
           NULL                as RepositoryID,
           NULL                as RepositoryCode,
           NULL                as RepositoryName,
           NULL                as UnitID,
           NULL                as Quantity,
           NULL                as UnitPrice,
           NULL                as UnitPriceOriginal,
           NULL                as MainUnitID,
           NULL                as MainQuantity,
           NULL                as MainUnitPrice,
           NULL                as MainConvertRate,
           NULL                as Formula,
           NULL                as ConfrontID,
           NULL                as ConfrontDetailID,
           NULL                as PPOrderDetailId,
           NULL                as PPOrderDetailQuantity,
           NULL                as RepositoryAccount,
           NULL                as CostAccount,
           NULL                as vatDescription,
           NULL                as invoiceNo,
           NULL                as OWPrice,
           NULL                as OWAmount,
           NULL                as LotNo,
           NULL                as ExpiryDate,
           a.DepartmentID,
           a.ExpenseItemID,
           a.BudgetItemID,
           a.CostSetID,
           a.ContractID,
           NULL                as StatisticsCodeID,
           null                as importTaxAmount,
           null                as importTaxAmountOriginal,
           null                as importTaxAccount,
           null                as specialConsumeTaxAmount,
           null                as specialConsumeTaxAmountOriginal,
           null                as specialConsumeTaxAccount,
           a.OrderPriority,
           NULL                as IsPromotion,
           NULL                as InwardAmount,
           NULL                as FromRepositoryID,
           NULL                as ToRepositoryID,
           'FAIncrementDetail' AS RefTable
    FROM dbo.FAIncrementDetail a
             left join AccountingObject d on d.ID = a.AccountingObjectID
/* =======================================================================*/
    UNION ALL
    SELECT NEWID()             AS ID,
           a.ID                as RefID,
           a.FADecrementID     as RefParentID,
           NULL                as CreditAccount,
           NULL                as DebitAccount,
           NULL                as BankAccountDetailID,
           NULL                as BankAccount,
           NULL                as BankName,
           NULL                as Amount,
           NULL                as AmountOriginal,
           NULL                as VATRate,
           NULL                as VATAccount,
           NULL                as DeductionDebitAccount,
           NULL                as VATAmount,
           NULL                as VATAmountOriginal,
           NULL                as DiscountRate,
           NULL                as DiscountAccount,
           NULL                as DiscountAmount,
           NULL                as DiscountAmountOriginal,
           NULL                as ExportTaxAmount,
           NULL                as ExportTaxAmountAccount,
           NULL                as ExportTaxAccountCorresponding,
           NULL                as Description,
           NULL                as AccountingObjectID,
           NULL                as AccountingObjectCode,
           NULL                as AccountingObjectName,
           NULL                as AccountingObjectAddress,
           NULL                as DebitAccountingObjectID,
           NULL                as DebitAccountingObjectCode,
           NULL                as DebitAccountingObjectName,
           NULL                as DebitAccountingObjectAddress,
           NULL                as CreditAccountingObjectID,
           NULL                as CreditAccountingObjectCode,
           NULL                as CreditAccountingObjectName,
           NULL                as CreditAccountingObjectAddress,
           NULL                as EmployeeID,
           NULL                as EmployeeCode,
           NULL                as EmployeeName,
           NULL                as MaterialGoodsID,
           NULL                as MaterialGoodsCode,
           NULL                as MaterialGoodsName,
           NULL                as RepositoryID,
           NULL                as RepositoryCode,
           NULL                as RepositoryName,
           NULL                as UnitID,
           NULL                as Quantity,
           NULL                as UnitPrice,
           NULL                as UnitPriceOriginal,
           NULL                as MainUnitID,
           NULL                as MainQuantity,
           NULL                as MainUnitPrice,
           NULL                as MainConvertRate,
           NULL                as Formula,
           NULL                as ConfrontID,
           NULL                as ConfrontDetailID,
           NULL                as PPOrderDetailId,
           NULL                as PPOrderDetailQuantity,
           NULL                as RepositoryAccount,
           NULL                as CostAccount,
           NULL                as vatDescription,
           NULL                as invoiceNo,
           NULL                as OWPrice,
           NULL                as OWAmount,
           NULL                as LotNo,
           NULL                as ExpiryDate,
           a.DepartmentID,
           NULL                as ExpenseItemID,
           NULL                as BudgetItemID,
           NULL                as CostSetID,
           NULL                as ContractID,
           NULL                as StatisticsCodeID,
           null                as importTaxAmount,
           null                as importTaxAmountOriginal,
           null                as importTaxAccount,
           null                as specialConsumeTaxAmount,
           null                as specialConsumeTaxAmountOriginal,
           null                as specialConsumeTaxAccount,
           a.OrderPriority,
           NULL                as IsPromotion,
           NULL                as InwardAmount,
           NULL                as FromRepositoryID,
           NULL                as ToRepositoryID,
           'FADecrementDetail' AS RefTable
    FROM dbo.FADecrementDetail a
/* =======================================================================*/
    UNION ALL
    SELECT NEWID()              AS ID,
           a.ID                 as RefID,
           a.FAAdjustmentID     as RefParentID,
           a.CreditAccount,
           a.DebitAccount,
           NULL                 as BankAccountDetailID,
           NULL                 as BankAccount,
           NULL                 as BankName,
           a.Amount,
           NULL                 as AmountOriginal,
           NULL                 as VATRate,
           NULL                 as VATAccount,
           NULL                 as DeductionDebitAccount,
           NULL                 as VATAmount,
           NULL                 as VATAmountOriginal,
           NULL                 as DiscountRate,
           NULL                 as DiscountAccount,
           NULL                 as DiscountAmount,
           NULL                 as DiscountAmountOriginal,
           NULL                 as ExportTaxAmount,
           NULL                 as ExportTaxAmountAccount,
           NULL                 as ExportTaxAccountCorresponding,
           a.Description,
           a.AccountingObjectID,
           d.AccountingObjectCode,
           d.AccountingObjectName,
           d.AccountingObjectAddress,
           NULL                 as DebitAccountingObjectID,
           NULL                 as DebitAccountingObjectCode,
           NULL                 as DebitAccountingObjectName,
           NULL                 as DebitAccountingObjectAddress,
           NULL                 as CreditAccountingObjectID,
           NULL                 as CreditAccountingObjectCode,
           NULL                 as CreditAccountingObjectName,
           NULL                 as CreditAccountingObjectAddress,
           NULL                 as EmployeeID,
           NULL                 as EmployeeCode,
           NULL                 as EmployeeName,
           NULL                 as MaterialGoodsID,
           NULL                 as MaterialGoodsCode,
           NULL                 as MaterialGoodsName,
           NULL                 as RepositoryID,
           NULL                 as RepositoryCode,
           NULL                 as RepositoryName,
           NULL                 as UnitID,
           NULL                 as Quantity,
           NULL                 as UnitPrice,
           NULL                 as UnitPriceOriginal,
           NULL                 as MainUnitID,
           NULL                 as MainQuantity,
           NULL                 as MainUnitPrice,
           NULL                 as MainConvertRate,
           NULL                 as Formula,
           NULL                 as ConfrontID,
           NULL                 as ConfrontDetailID,
           NULL                 as PPOrderDetailId,
           NULL                 as PPOrderDetailQuantity,
           NULL                 as RepositoryAccount,
           NULL                 as CostAccount,
           NULL                 as vatDescription,
           NULL                 as invoiceNo,
           NULL                 as OWPrice,
           NULL                 as OWAmount,
           NULL                 as LotNo,
           NULL                 as ExpiryDate,
           a.DepartmentID,
           a.ExpenseItemID,
           a.BudgetItemID,
           a.CostSetID,
           a.ContractID,
           a.StatisticsCodeID,
           null                 as importTaxAmount,
           null                 as importTaxAmountOriginal,
           null                 as importTaxAccount,
           null                 as specialConsumeTaxAmount,
           null                 as specialConsumeTaxAmountOriginal,
           null                 as specialConsumeTaxAccount,
           a.OrderPriority,
           NULL                 as IsPromotion,
           NULL                 as InwardAmount,
           NULL                 as FromRepositoryID,
           NULL                 as ToRepositoryID,
           'FAAdjustmentDetail' AS RefTable
    FROM dbo.FAAdjustmentDetail a
             left join AccountingObject d on d.ID = a.AccountingObjectID
/* =======================================================================*/
    UNION ALL
    SELECT NEWID()                AS ID,
           a.ID                   as RefID,
           a.FATransferID         as RefParentID,
           NULL                   as CreditAccount,
           NULL                   as DebitAccount,
           NULL                   as BankAccountDetailID,
           NULL                   as BankAccount,
           NULL                   as BankName,
           NULL                   as Amount,
           NULL                   as AmountOriginal,
           NULL                   as VATRate,
           NULL                   as VATAccount,
           NULL                   as DeductionDebitAccount,
           NULL                   as VATAmount,
           NULL                   as VATAmountOriginal,
           NULL                   as DiscountRate,
           NULL                   as DiscountAccount,
           NULL                   as DiscountAmount,
           NULL                   as DiscountAmountOriginal,
           NULL                   as ExportTaxAmount,
           NULL                   as ExportTaxAmountAccount,
           NULL                   as ExportTaxAccountCorresponding,
           a.Description,
           NULL                   as AccountingObjectID,
           NULL                   as AccountingObjectCode,
           NULL                   as AccountingObjectName,
           NULL                   as AccountingObjectAddress,
           NULL                   as DebitAccountingObjectID,
           NULL                   as DebitAccountingObjectCode,
           NULL                   as DebitAccountingObjectName,
           NULL                   as DebitAccountingObjectAddress,
           NULL                   as CreditAccountingObjectID,
           NULL                   as CreditAccountingObjectCode,
           NULL                   as CreditAccountingObjectName,
           NULL                   as CreditAccountingObjectAddress,
           a.EmployeeID,
           e.AccountingObjectCode as EmployeeCode,
           e.AccountingObjectName as EmployeeName,
           NULL                   as MaterialGoodsID,
           NULL                   as MaterialGoodsCode,
           NULL                   as MaterialGoodsName,
           NULL                   as RepositoryID,
           NULL                   as RepositoryCode,
           NULL                   as RepositoryName,
           NULL                   as UnitID,
           NULL                   as Quantity,
           NULL                   as UnitPrice,
           NULL                   as UnitPriceOriginal,
           NULL                   as MainUnitID,
           NULL                   as MainQuantity,
           NULL                   as MainUnitPrice,
           NULL                   as MainConvertRate,
           NULL                   as Formula,
           NULL                   as ConfrontID,
           NULL                   as ConfrontDetailID,
           NULL                   as PPOrderDetailId,
           NULL                   as PPOrderDetailQuantity,
           NULL                   as RepositoryAccount,
           a.CostAccount,
           NULL                   as vatDescription,
           NULL                   as invoiceNo,
           NULL                   as OWPrice,
           NULL                   as OWAmount,
           NULL                   as LotNo,
           NULL                   as ExpiryDate,
           NULL                   as DepartmentID,
           a.ExpenseItemID,
           a.BudgetItemID,
           a.CostSetID,
           NULL                   as ContractID,
           a.StatisticsCodeID,
           null                   as importTaxAmount,
           null                   as importTaxAmountOriginal,
           null                   as importTaxAccount,
           null                   as specialConsumeTaxAmount,
           null                   as specialConsumeTaxAmountOriginal,
           null                   as specialConsumeTaxAccount,
           a.OrderPriority,
           NULL                   as IsPromotion,
           NULL                   as InwardAmount,
           NULL                   as FromRepositoryID,
           NULL                   as ToRepositoryID,
           'FATransferDetail'     AS RefTable
    FROM dbo.FATransferDetail a
             left join AccountingObject e on e.ID = a.EmployeeID
/* =======================================================================*/
    UNION ALL
    SELECT NEWID()                AS ID,
           a.ID                   as RefID,
           a.FADepreciationID     as RefParentID,
           NULL                   as CreditAccount,
           NULL                   as DebitAccount,
           NULL                   as BankAccountDetailID,
           NULL                   as BankAccount,
           NULL                   as BankName,
           a.Amount,
           NULL                   as AmountOriginal,
           NULL                   as VATRate,
           NULL                   as VATAccount,
           NULL                   as DeductionDebitAccount,
           NULL                   as VATAmount,
           NULL                   as VATAmountOriginal,
           NULL                   as DiscountRate,
           NULL                   as DiscountAccount,
           NULL                   as DiscountAmount,
           NULL                   as DiscountAmountOriginal,
           NULL                   as ExportTaxAmount,
           NULL                   as ExportTaxAmountAccount,
           NULL                   as ExportTaxAccountCorresponding,
           NULL                   as Description,
           NULL                   as AccountingObjectID,
           NULL                   as AccountingObjectCode,
           NULL                   as AccountingObjectName,
           NULL                   as AccountingObjectAddress,
           NULL                   as DebitAccountingObjectID,
           NULL                   as DebitAccountingObjectCode,
           NULL                   as DebitAccountingObjectName,
           NULL                   as DebitAccountingObjectAddress,
           NULL                   as CreditAccountingObjectID,
           NULL                   as CreditAccountingObjectCode,
           NULL                   as CreditAccountingObjectName,
           NULL                   as CreditAccountingObjectAddress,
           NULL                   as EmployeeID,
           NULL                   as EmployeeCode,
           NULL                   as EmployeeName,
           NULL                   as MaterialGoodsID,
           NULL                   as MaterialGoodsCode,
           NULL                   as MaterialGoodsName,
           NULL                   as RepositoryID,
           NULL                   as RepositoryCode,
           NULL                   as RepositoryName,
           NULL                   as UnitID,
           NULL                   as Quantity,
           NULL                   as UnitPrice,
           NULL                   as UnitPriceOriginal,
           NULL                   as MainUnitID,
           NULL                   as MainQuantity,
           NULL                   as MainUnitPrice,
           NULL                   as MainConvertRate,
           NULL                   as Formula,
           NULL                   as ConfrontID,
           NULL                   as ConfrontDetailID,
           NULL                   as PPOrderDetailId,
           NULL                   as PPOrderDetailQuantity,
           NULL                   as RepositoryAccount,
           NULL                   as CostAccount,
           NULL                   as vatDescription,
           NULL                   as invoiceNo,
           NULL                   as OWPrice,
           NULL                   as OWAmount,
           NULL                   as LotNo,
           NULL                   as ExpiryDate,
           NULL                   as DepartmentID,
           NULL                   as ExpenseItemID,
           NULL                   as BudgetItemID,
           NULL                   as CostSetID,
           NULL                   as ContractID,
           NULL                   as StatisticsCodeID,
           null                   as importTaxAmount,
           null                   as importTaxAmountOriginal,
           null                   as importTaxAccount,
           null                   as specialConsumeTaxAmount,
           null                   as specialConsumeTaxAmountOriginal,
           null                   as specialConsumeTaxAccount,
           a.OrderPriority,
           NULL                   as IsPromotion,
           NULL                   as InwardAmount,
           NULL                   as FromRepositoryID,
           NULL                   as ToRepositoryID,
           'FADepreciationDetail' AS RefTable
    FROM dbo.FADepreciationDetail a
/* =======================================================================*/
    UNION ALL
    SELECT NEWID()                      AS ID,
           a.ID                         as RefID,
           a.GOtherVoucherID            as RefParentID,
           a.CreditAccount,
           a.DebitAccount,
           a.BankAccountDetailID,
           ba.BankAccount,
           ba.BankName,
           a.Amount,
           a.AmountOriginal,
           NULL                         as VATRate,
           NULL                         as VATAccount,
           NULL                         as DeductionDebitAccount,
           NULL                         as VATAmount,
           NULL                         as VATAmountOriginal,
           NULL                         as DiscountRate,
           NULL                         as DiscountAccount,
           NULL                         as DiscountAmount,
           NULL                         as DiscountAmountOriginal,
           NULL                         as ExportTaxAmount,
           NULL                         as ExportTaxAmountAccount,
           NULL                         as ExportTaxAccountCorresponding,
           a.Description,
           NULL                         as AccountingObjectID,
           NULL                         as AccountingObjectCode,
           NULL                         as AccountingObjectName,
           NULL                         as AccountingObjectAddress,
           acc1.ID                      as DebitAccountingObjectID,
           acc1.AccountingObjectCode    as DebitAccountingObjectCode,
           acc1.AccountingObjectName    as DebitAccountingObjectName,
           acc1.AccountingObjectAddress as DebitAccountingObjectAddress,
           acc2.ID                      as CreditAccountingObjectID,
           acc2.AccountingObjectCode    as CreditAccountingObjectCode,
           acc2.AccountingObjectName    as CreditAccountingObjectName,
           acc2.AccountingObjectAddress as CreditAccountingObjectAddress,
           a.EmployeeID,
           e.AccountingObjectCode       as EmployeeCode,
           e.AccountingObjectName       as EmployeeName,
           NULL                         as MaterialGoodsID,
           NULL                         as MaterialGoodsCode,
           NULL                         as MaterialGoodsName,
           NULL                         as RepositoryID,
           NULL                         as RepositoryCode,
           NULL                         as RepositoryName,
           NULL                         as UnitID,
           NULL                         as Quantity,
           NULL                         as UnitPrice,
           NULL                         as UnitPriceOriginal,
           NULL                         as MainUnitID,
           NULL                         as MainQuantity,
           NULL                         as MainUnitPrice,
           NULL                         as MainConvertRate,
           NULL                         as Formula,
           NULL                         as ConfrontID,
           NULL                         as ConfrontDetailID,
           NULL                         as PPOrderDetailId,
           NULL                         as PPOrderDetailQuantity,
           NULL                         as RepositoryAccount,
           NULL                         as CostAccount,
           NULL                         as vatDescription,
           NULL                         as invoiceNo,
           NULL                         as OWPrice,
           NULL                         as OWAmount,
           NULL                         as LotNo,
           NULL                         as ExpiryDate,
           a.DepartmentID,
           a.ExpenseItemID,
           a.BudgetItemID,
           a.CostSetID,
           a.ContractID,
           a.StatisticsCodeID,
           null                         as importTaxAmount,
           null                         as importTaxAmountOriginal,
           null                         as importTaxAccount,
           null                         as specialConsumeTaxAmount,
           null                         as specialConsumeTaxAmountOriginal,
           null                         as specialConsumeTaxAccount,
           a.OrderPriority,
           NULL                         as IsPromotion,
           NULL                         as InwardAmount,
           NULL                         as FromRepositoryID,
           NULL                         as ToRepositoryID,
           'GOtherVoucherDetail'        AS RefTable
    FROM dbo.GOtherVoucherDetail a
             left join AccountingObject e on e.ID = a.EmployeeID
             left join BankAccountDetail ba on ba.ID = a.BankAccountDetailID
             left join AccountingObject acc1 on acc1.ID = a.DebitAccountingObjectID
             left join AccountingObject acc2 on acc2.ID = a.CreditAccountingObjectID
go

