/*Author Hautv*/
CREATE view [dbo].[ViewCheckConstraint]
as
    select NEWID()     as ID,
           a.ID        as DetailID,
           b.ID        as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           b.PostedDate,
           b.CurrencyID,
           b.TotalAmountOriginal,
           b.TotalAmount,
           b.Reason,
           a.Description,
           b.Recorded,
           a.AccountingObjectID,
           b.EmployeeID,
           NULL        as MaterialGoodsID,
           NULL        as RepositoryID,
           a.BankAccountDetailID,
           NULL        as CreditCardID,
           NULL        as ToolsID,
           NULL        as FixedAssetID,
           a.CostSetID,
           a.ExpenseItemID,
           a.StatisticsCodeID,
           a.BudgetItemID,
           a.ContractID,
           a.DepartmentID,
           b.PaymentClauseID,
           b.TransportMethodID,
           'MCReceipt' as RefTable
    from MCReceiptDetail a
             left join MCReceipt b on a.MCReceiptID = b.ID
             left join Type c on b.TypeID = c.ID
    union all
    select NEWID()     as ID,
           a.ID        as DetailID,
           b.ID        as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           b.PostedDate,
           b.CurrencyID,
           b.TotalAmountOriginal,
           b.TotalAmount,
           b.Reason,
           a.Description,
           b.Recorded,
           a.AccountingObjectID,
           b.EmployeeID,
           NULL        as MaterialGoodsID,
           NULL        as RepositoryID,
           a.BankAccountDetailID,
           NULL        as CreditCardID,
           NULL        as ToolsID,
           NULL        as FixedAssetID,
           a.CostSetID,
           a.ExpenseItemID,
           a.StatisticsCodeID,
           a.BudgetItemID,
           a.ContractID,
           a.DepartmentID,
           b.PaymentClauseID,
           b.TransportMethodID,
           'MCPayment' as RefTable
    from MCPaymentDetail a
             left join MCPayment b on a.MCPaymentID = b.ID
             left join Type c on b.TypeID = c.ID
    union all
    select NEWID()         as ID,
           a.ID            as DetailID,
           b.ID            as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           b.PostedDate,
           b.CurrencyID,
           b.TotalAmountOriginal,
           b.TotalAmount,
           b.Reason,
           a.Description,
           b.Recorded,
           a.AccountingObjectID,
           b.EmployeeID,
           NULL            as MaterialGoodsID,
           NULL            as RepositoryID,
           b.BankAccountDetailID,
           NULL            as CreditCardID,
           NULL            as ToolsID,
           NULL            as FixedAssetID,
           a.CostSetID,
           a.ExpenseItemID,
           a.StatisticsCodeID,
           a.BudgetItemID,
           a.ContractID,
           a.DepartmentID,
           b.PaymentClauseID,
           b.TransportMethodID,
           'MBTellerPaper' as RefTable
    from MBTellerPaperDetail a
             left join MBTellerPaper b on a.MBTellerPaperID = b.ID
             left join Type c on b.TypeID = c.ID
    union all
    select NEWID()        as ID,
           a.ID           as DetailID,
           b.ID           as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           b.PostedDate,
           b.CurrencyID,
           b.TotalAmountOriginal,
           b.TotalAmount,
           b.Reason,
           a.Description,
           b.Recorded,
           a.AccountingObjectID,
           b.EmployeeID,
           NULL           as MaterialGoodsID,
           NULL           as RepositoryID,
           NULL           as BankAccountDetailID,
           b.CreditCardID,
           NULL           as ToolsID,
           NULL           as FixedAssetID,
           a.CostSetID,
           a.ExpenseItemID,
           a.StatisticsCodeID,
           a.BudgetItemID,
           a.ContractID,
           a.DepartmentID,
           b.PaymentClauseID,
           b.TransportMethodID,
           'MBCreditCard' as RefTable
    from MBCreditCardDetail a
             left join MBCreditCard b on a.MBCreditCardID = b.ID
             left join Type c on b.TypeID = c.ID
    union all
    select NEWID()     as ID,
           a.ID        as DetailID,
           b.ID        as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           b.PostedDate,
           b.CurrencyID,
           b.TotalAmountOriginal,
           b.TotalAmount,
           b.Reason,
           a.Description,
           b.Recorded,
           a.AccountingObjectID,
           b.EmployeeID,
           NULL        as MaterialGoodsID,
           NULL        as RepositoryID,
           NULL        as BankAccountDetailID,
           NULL        as CreditCardID,
           NULL        as ToolsID,
           NULL        as FixedAssetID,
           a.CostSetID,
           a.ExpenseItemID,
           a.StatisticsCodeID,
           a.BudgetItemID,
           a.ContractID,
           a.DepartmentID,
           b.PaymentClauseID,
           b.TransportMethodID,
           'MBDeposit' as RefTable
    from MBDepositDetail a
             left join MBDeposit b on a.MBDepositID = b.ID
             left join Type c on b.TypeID = c.ID
    union all
    select NEWID()              as ID,
           a.ID                 as DetailID,
           b.ID                 as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           b.PostedDate,
           a.CurrencyID,
           b.TotalAmountOriginal,
           b.TotalAmount,
           b.Reason,
           NULL                 as Description,
           b.Recorded,
           a.AccountingObjectID,
           b.EmployeeID,
           NULL                 as MaterialGoodsID,
           NULL                 as RepositoryID,
           NULL                 as BankAccountDetailID,
           NULL                 as CreditCardID,
           NULL                 as ToolsID,
           NULL                 as FixedAssetID,
           a.CostSetID,
           a.ExpenseItemID,
           a.StatisticsCodeID,
           a.BudgetItemID,
           a.ContractID,
           a.DepartmentID,
           NULL                 as PaymentClauseID,
           NULL                 as TransportMethodID,
           'MBInternalTransfer' as RefTable
    from MBInternalTransferDetail a
             left join MBInternalTransfer b on a.MBInternalTransferID = b.ID
             left join Type c on b.TypeID = c.ID
    union all
    select NEWID()   as ID,
           a.ID      as DetailID,
           b.ID      as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           b.TypeLedger,
           b.No      as NoMBook,
           b.No      as NoFBook,
           b.Date,
           NULL      as PostedDate,
           b.CurrencyID,
           NULL      as TotalAmountOriginal,
           NULL      as TotalAmount,
           NULL      as Reason,
           a.Description,
           NULL      as Recorded,
           NULL      as AccountingObjectID,
           NULL      as EmployeeID,
           NULL      as MaterialGoodsID,
           NULL      as RepositoryID,
           NULL      as BankAccountDetailID,
           NULL      as CreditCardID,
           NULL      as ToolsID,
           NULL      as FixedAssetID,
           NULL      as CostSetID,
           NULL      as ExpenseItemID,
           NULL      as StatisticsCodeID,
           NULL      as BudgetItemID,
           NULL      as ContractID,
           NULL      as DepartmentID,
           NULL      as PaymentClauseID,
           NULL      as TransportMethodID,
           'MCAudit' as RefTable
    from MCAuditDetail a
             left join MCAudit b on a.MCAuditID = b.ID
             left join Type c on b.TypeID = c.ID
    union all
    select NEWID()   as ID,
           a.ID      as DetailID,
           b.ID      as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           2         as TypeLedger,
           b.No      as NoMBook,
           b.No      as NoFBook,
           b.Date,
           NULL      as PostedDate,
           b.CurrencyID,
           b.TotalAmountOriginal,
           b.TotalAmount,
           b.Reason,
           a.Description,
           NULL      as Recorded,
           b.AccountingObjectID,
           b.EmployeeID,
           a.MaterialGoodsID,
           NULL      as RepositoryID,
           NULL      as BankAccountDetailID,
           NULL      as CreditCardID,
           NULL      as ToolsID,
           NULL      as FixedAssetID,
           NULL      as CostSetID,
           NULL      as ExpenseItemID,
           NULL      as StatisticsCodeID,
           NULL      as BudgetItemID,
           NULL      as ContractID,
           NULL      as DepartmentID,
           NULL      as PaymentClauseID,
           NULL      as TransportMethodID,
           'PPOrder' as RefTable
    from PPOrderDetail a
             left join PPOrder b on a.PPOrderID = b.ID
             left join Type c on b.TypeID = c.ID
    union all
    select NEWID()     as ID,
           a.ID        as DetailID,
           b.ID        as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           b.PostedDate,
           b.CurrencyID,
           b.TotalAmountOriginal,
           b.TotalAmount,
           b.Reason,
           a.Description,
           b.Recorded,
           b.AccountingObjectID,
           b.EmployeeID,
           a.MaterialGoodsID,
           a.RepositoryID,
           NULL        as BankAccountDetailID,
           NULL        as CreditCardID,
           NULL        as ToolsID,
           NULL        as FixedAssetID,
           a.CostSetID,
           a.ExpenseItemID,
           NULL        as StatisticsCodeID,
           a.BudgetItemID,
           a.ContractID,
           a.DepartmentID,
           b.PaymentClauseID,
           b.TransportMethodID,
           'PPInvoice' as RefTable
    from PPInvoiceDetail a
             left join PPInvoice b on a.PPInvoiceID = b.ID
             left join Type c on b.TypeID = c.ID
    union all
    select NEWID()     as ID,
           a.ID        as DetailID,
           b.ID        as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           b.PostedDate,
           b.CurrencyID,
           b.TotalAmountOriginal,
           b.TotalAmount,
           b.Reason,
           a.Description,
           b.Recorded,
           b.AccountingObjectID,
           b.EmployeeID,
           a.MaterialGoodsID,
           NULL        as RepositoryID,
           NULL        as BankAccountDetailID,
           NULL        as CreditCardID,
           NULL        as ToolsID,
           NULL        as FixedAssetID,
           a.CostSetID,
           a.ExpenseItemID,
           a.StatisticsCodeID,
           a.BudgetItemID,
           a.ContractID,
           a.DepartmentID,
           b.PaymentClauseID,
           NULL        as TransportMethodID,
           'PPService' as RefTable
    from PPServiceDetail a
             left join PPService b on a.PPServiceID = b.ID
             left join Type c on b.TypeID = c.ID
    union all
    select NEWID()            as ID,
           a.ID               as DetailID,
           b.ID               as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           b.PostedDate,
           b.CurrencyID,
           b.TotalAmountOriginal,
           b.TotalAmount,
           b.Reason,
           a.Description,
           b.Recorded,
           b.AccountingObjectID,
           b.EmployeeID,
           a.MaterialGoodsID,
           a.RepositoryID,
           NULL               as BankAccountDetailID,
           NULL               as CreditCardID,
           NULL               as ToolsID,
           NULL               as FixedAssetID,
           a.CostSetID,
           a.ExpenseItemID,
           a.StatisticsCodeID,
           a.BudgetItemID,
           a.ContractID,
           a.DepartmentID,
           b.PaymentClauseID,
           b.TransportMethodID,
           'PPDiscountReturn' as RefTable
    from PPDiscountReturnDetail a
             left join PPDiscountReturn b on a.PPDiscountReturnID = b.ID
             left join Type c on b.TypeID = c.ID
    union all
    select NEWID()   as ID,
           a.ID      as DetailID,
           b.ID      as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           2         as TypeLedger,
           b.No      as NoMBook,
           b.No      as NoFBook,
           b.Date,
           NULL      as PostedDate,
           b.CurrencyID,
           b.TotalAmountOriginal,
           b.TotalAmount,
           b.Reason,
           a.Description,
           NULL      as Recorded,
           b.AccountingObjectID,
           b.EmployeeID,
           a.MaterialGoodsID,
           NULL      as RepositoryID,
           NULL      as BankAccountDetailID,
           NULL      as CreditCardID,
           NULL      as ToolsID,
           NULL      as FixedAssetID,
           NULL      as CostSetID,
           NULL      as ExpenseItemID,
           NULL      as StatisticsCodeID,
           NULL      as BudgetItemID,
           NULL      as ContractID,
           NULL      as DepartmentID,
           b.PaymentClauseID,
           NULL      as TransportMethodID,
           'SAQuote' as RefTable
    from SAQuoteDetail a
             left join SAQuote b on a.SAQuoteID = b.ID
             left join Type c on b.TypeID = c.ID
    union all
    select NEWID()   as ID,
           a.ID      as DetailID,
           b.ID      as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           2         as TypeLedger,
           b.No      as NoMBook,
           b.No      as NoFBook,
           b.Date,
           NULL      as PostedDate,
           b.CurrencyID,
           b.TotalAmountOriginal,
           b.TotalAmount,
           b.Reason,
           a.Description,
           NULL      as Recorded,
           b.AccountingObjectID,
           b.EmployeeID,
           a.MaterialGoodsID,
           NULL      as RepositoryID,
           NULL      as BankAccountDetailID,
           NULL      as CreditCardID,
           NULL      as ToolsID,
           NULL      as FixedAssetID,
           NULL      as CostSetID,
           NULL      as ExpenseItemID,
           NULL      as StatisticsCodeID,
           NULL      as BudgetItemID,
           NULL      as ContractID,
           NULL      as DepartmentID,
           NULL      as PaymentClauseID,
           NULL      as TransportMethodID,
           'SAOrder' as RefTable
    from SAOrderDetail a
             left join SAOrder b on a.SAOrderID = b.ID
             left join Type c on b.TypeID = c.ID
    union all
    select NEWID()     as ID,
           a.ID        as DetailID,
           b.ID        as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           b.PostedDate,
           b.CurrencyID,
           b.TotalAmountOriginal,
           b.TotalAmount,
           b.Reason,
           a.Description,
           b.Recorded,
           b.AccountingObjectID,
           b.EmployeeID,
           a.MaterialGoodsID,
           a.RepositoryID,
           NULL        as BankAccountDetailID,
           NULL        as CreditCardID,
           NULL        as ToolsID,
           NULL        as FixedAssetID,
           a.CostSetID,
           a.ExpenseItemID,
           a.StatisticsCodeID,
           a.BudgetItemID,
           a.ContractID,
           a.DepartmentID,
           b.PaymentClauseID,
           b.TransportMethodID,
           'SAInvoice' as RefTable
    from SAInvoiceDetail a
             left join SAInvoice b on a.SAInvoiceID = b.ID
             left join Type c on b.TypeID = c.ID
    union all
    select NEWID()       as ID,
           a.ID          as DetailID,
           b.ID          as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           b.TypeLedger,
           Null          as NoMBook,
           NULL          as NoFBook,
           b.InvoiceDate as Date,
           NULL          as PostedDate,
           b.CurrencyID,
           b.TotalAmountOriginal,
           b.TotalAmount,
           b.Reason,
           a.Description,
           NULL          as Recorded,
           b.AccountingObjectID,
           NULL          as EmployeeID,
           a.MaterialGoodsID,
           NULL          as RepositoryID,
           NULL          as BankAccountDetailID,
           NULL          as CreditCardID,
           NULL          as ToolsID,
           NULL          as FixedAssetID,
           NULL          as CostSetID,
           NULL          as ExpenseItemID,
           NULL          as StatisticsCodeID,
           NULL          as BudgetItemID,
           NULL          as ContractID,
           NULL          as DepartmentID,
           NULL          as PaymentClauseID,
           NULL          as TransportMethodID,
           'SABill'      as RefTable
    from SABillDetail a
             left join SABill b on a.SABillID = b.ID
             left join Type c on b.TypeID = c.ID

    union all
    select NEWID()    as ID,
           a.ID       as DetailID,
           b.ID       as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           b.PostedDate,
           b.CurrencyID,
           b.TotalAmountOriginal,
           b.TotalAmount,
           b.Reason,
           a.Description,
           b.Recorded,
           b.AccountingObjectID,
           b.EmployeeID,
           a.MaterialGoodsID,
           a.RepositoryID,
           NULL       as BankAccountDetailID,
           NULL       as CreditCardID,
           NULL       as ToolsID,
           NULL       as FixedAssetID,
           a.CostSetID,
           a.ExpenseItemID,
           a.StatisticsCodeID,
           a.BudgetItemID,
           a.ContractID,
           a.DepartmentID,
           NULL       as PaymentClauseID,
           NULL       as TransportMethodID,
           'SAReturn' as RefTable
    from SAReturnDetail a
             left join SAReturn b on a.SAReturnID = b.ID
             left join Type c on b.TypeID = c.ID
    union all
    select NEWID()           as ID,
           a.ID              as DetailID,
           b.ID              as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           b.PostedDate,
           b.CurrencyID,
           b.TotalAmountOriginal,
           b.TotalAmount,
           b.Reason,
           a.Description,
           b.Recorded,
           b.AccountingObjectID,
           b.EmployeeID,
           a.MaterialGoodsID,
           a.RepositoryID,
           NULL              as BankAccountDetailID,
           NULL              as CreditCardID,
           NULL              as ToolsID,
           NULL              as FixedAssetID,
           a.CostSetID,
           a.ExpenseItemID,
           a.StatisticsCodeID,
           a.BudgetItemID,
           a.ContractID,
           a.DepartmentID,
           NULL              as PaymentClauseID,
           b.TransportMethodID,
           'RSInwardOutward' as RefTable
    from RSInwardOutwardDetail a
             left join RSInwardOutward b on a.RSInwardOutwardID = b.ID
             left join Type c on b.TypeID = c.ID
    union all
    select NEWID()                   as ID,
           a.ID                      as DetailID,
           b.ID                      as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           2                         as TypeLedger,
           b.No                      as NoMBook,
           b.No                      as NoFBook,
           b.Date,
           NULL                      as PostedDate,
           NULL                      as CurrencyID,
           NULL                      as TotalAmountOriginal,
           NULL                      as TotalAmount,
           b.Reason,
           a.Description,
           NULL                      as Recorded,
           NULL                      as AccountingObjectID,
           NULL                      as EmployeeID,
           a.MaterialGoodsID,
           a.RepositoryID,
           NULL                      as BankAccountDetailID,
           NULL                      as CreditCardID,
           NULL                      as ToolsID,
           NULL                      as FixedAssetID,
           NULL                      as CostSetID,
           NULL                      as ExpenseItemID,
           NULL                      as StatisticsCodeID,
           NULL                      as BudgetItemID,
           NULL                      as ContractID,
           NULL                      as DepartmentID,
           NULL                      as PaymentClauseID,
           NULL                      as TransportMethodID,
           'RSAssemblyDismantlement' as RefTable
    from RSAssemblyDismantlementDetail a
             left join RSAssemblyDismantlement b on a.RSAssemblyDismantlementID = b.ID
             left join Type c on b.TypeID = c.ID
    union all
    select NEWID()             as ID,
           a.ID                as DetailID,
           b.ID                as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           2                   as TypeLedger,
           b.No                as NoMBook,
           b.No                as NoFBook,
           b.Date,
           NULL                as PostedDate,
           NULL                as CurrencyID,
           NULL                as TotalAmountOriginal,
           NULL                as TotalAmount,
           b.Reason,
           a.Description,
           NULL                as Recorded,
           NULL                as AccountingObjectID,
           NULL                as EmployeeID,
           a.MaterialGoodsID,
           NULL                as RepositoryID,
           NULL                as BankAccountDetailID,
           NULL                as CreditCardID,
           NULL                as ToolsID,
           NULL                as FixedAssetID,
           a.CostSetID,
           NULL                as ExpenseItemID,
           NULL                as StatisticsCodeID,
           NULL                as BudgetItemID,
           a.ContractID,
           NULL                as DepartmentID,
           NULL                as PaymentClauseID,
           NULL                as TransportMethodID,
           'RSProductionOrder' as RefTable
    from RSProductionOrderDetail a
             left join RSProductionOrder b on a.RSProductionOrderID = b.ID
             left join Type c on b.TypeID = c.ID
    union all
    select NEWID()      as ID,
           a.ID         as DetailID,
           b.ID         as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           d.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           b.PostedDate,
           c.CurrencyID,
           b.TotalAmountOriginal,
           b.TotalAmount,
           NULL         as Reason,
           a.Description,
           b.Recorded,
           b.AccountingObjectID,
           NULL         as EmployeeID,
           a.MaterialGoodsID,
           NULL         as RepositoryID,
           NULL         as BankAccountDetailID,
           NULL         as CreditCardID,
           NULL         as ToolsID,
           NULL         as FixedAssetID,
           a.CostSetID,
           a.ExpenseItemID,
           a.StatisticsCodeID,
           a.BudgetItemID,
           NULL         as ContractID,
           a.DepartmentID,
           NULL         as PaymentClauseID,
           b.TransportMethodID,
           'RSTransfer' as RefTable
    from RSTransferDetail a
             left join RSTransfer b on a.RSTransferID = b.ID
             INNER JOIN
         dbo.EbOrganizationUnit c ON b.CompanyID = c.ID
             left join Type d on b.TypeID = d.ID
    union all
    select NEWID()       as ID,
           a.ID          as DetailID,
           b.ID          as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           NULL          as PostedDate,
           NULL          as CurrencyID,
           NULL          as TotalAmountOriginal,
           b.TotalAmount,
           b.Reason,
           a.Description,
           b.Recorded,
           NULL          as AccountingObjectID,
           NULL          as EmployeeID,
           NULL          as MaterialGoodsID,
           NULL          as RepositoryID,
           NULL          as BankAccountDetailID,
           NULL          as CreditCardID,
           a.ToolsID,
           NULL          as FixedAssetID,
           a.CostSetID,
           a.ExpenseItemID,
           NULL          as StatisticsCodeID,
           a.BudgetItemID,
           a.ContractID,
           a.DepartmentID,
           NULL          as PaymentClauseID,
           NULL          as TransportMethodID,
           'TIIncrement' as RefTable
    from TIIncrementDetail a
             left join TIIncrement b on a.TIIncrementID = b.ID
             left join Type c on b.TypeID = c.ID
    union all
    select NEWID()       as ID,
           a.ID          as DetailID,
           b.ID          as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           d.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           NULL          as PostedDate,
           c.CurrencyID,
           b.TotalAmount as TotalAmountOriginal,
           b.TotalAmount,
           b.Reason,
           a.Description,
           b.Recorded,
           NULL          as AccountingObjectID,
           NULL          as EmployeeID,
           NULL          as MaterialGoodsID,
           NULL          as RepositoryID,
           NULL          as BankAccountDetailID,
           NULL          as CreditCardID,
           a.ToolsID,
           NULL          as FixedAssetID,
           NULL          as CostSetID,
           NULL          as ExpenseItemID,
           NULL          as StatisticsCodeID,
           NULL          as BudgetItemID,
           NULL          as ContractID,
           NULL          as DepartmentID,
           NULL          as PaymentClauseID,
           NULL          as TransportMethodID,
           'TIDecrement' as RefTable
    from TIDecrementDetail a
             left join TIDecrement b on a.TIDecrementID = b.ID
             INNER JOIN
         dbo.EbOrganizationUnit c ON b.CompanyID = c.ID
             left join Type d on b.TypeID = d.ID
    union all
    select NEWID()        as ID,
           a.ID           as DetailID,
           b.ID           as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           d.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           b.PostedDate,
           c.CurrencyID,
           b.TotalAmount  as TotalAmountOriginal,
           b.TotalAmount,
           b.Reason,
           a.Description,
           b.Recorded,
           NULL           as AccountingObjectID,
           NULL           as EmployeeID,
           NULL           as MaterialGoodsID,
           NULL           as RepositoryID,
           NULL           as BankAccountDetailID,
           NULL           as CreditCardID,
           a.ToolsID,
           NULL           as FixedAssetID,
           NULL           as CostSetID,
           NULL           as ExpenseItemID,
           NULL           as StatisticsCodeID,
           NULL           as BudgetItemID,
           NULL           as ContractID,
           NULL           as DepartmentID,
           NULL           as PaymentClauseID,
           NULL           as TransportMethodID,
           'TIAdjustment' as RefTable
    from TIAdjustmentDetail a
             left join TIAdjustment b on a.TIAdjustmentID = b.ID
             INNER JOIN
         dbo.EbOrganizationUnit c ON b.CompanyID = c.ID
             left join Type d on b.TypeID = d.ID
    union all
    select NEWID()      as ID,
           a.ID         as DetailID,
           b.ID         as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           NULL         as PostedDate,
           NULL         as CurrencyID,
           NULL         as TotalAmountOriginal,
           NULL         as TotalAmount,
           b.Reason,
           a.Description,
           b.Recorded,
           NULL         as AccountingObjectID,
           NULL         as EmployeeID,
           NULL         as MaterialGoodsID,
           NULL         as RepositoryID,
           NULL         as BankAccountDetailID,
           NULL         as CreditCardID,
           a.ToolsID,
           NULL         as FixedAssetID,
           a.CostSetID,
           a.ExpenseItemID,
           NULL         as StatisticsCodeID,
           NULL         as BudgetItemID,
           NULL         as ContractID,
           NULL         as DepartmentID,
           NULL         as PaymentClauseID,
           NULL         as TransportMethodID,
           'TITransfer' as RefTable
    from TITransferDetail a
             left join TITransfer b on a.TITransferID = b.ID
             left join Type c on b.TypeID = c.ID
    union all
    select NEWID()   as ID,
           a.ID      as DetailID,
           b.ID      as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           NULL      as PostedDate,
           NULL      as CurrencyID,
           NULL      as TotalAmountOriginal,
           NULL      as TotalAmount,
           NULL      as Reason,
           NULL      as Description,
           NULL      as Recorded,
           NULL      as AccountingObjectID,
           NULL      as EmployeeID,
           NULL      as MaterialGoodsID,
           NULL      as RepositoryID,
           NULL      as BankAccountDetailID,
           NULL      as CreditCardID,
           a.ToolsID,
           NULL      as FixedAssetID,
           NULL      as CostSetID,
           NULL      as ExpenseItemID,
           NULL      as StatisticsCodeID,
           NULL      as BudgetItemID,
           NULL      as ContractID,
           a.DepartmentID,
           NULL      as PaymentClauseID,
           NULL      as TransportMethodID,
           'TIAudit' as RefTable
    from TIAuditDetail a
             left join TIAudit b on a.TIAuditID = b.ID
             left join Type c on b.TypeID = c.ID
    union all
    select NEWID()        as ID,
           a.ID           as DetailID,
           b.ID           as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           d.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           b.PostedDate,
           c.CurrencyID,
           b.TotalAmount  as TotalAmountOriginal,
           b.TotalAmount,
           b.Reason,
           a.Description,
           b.Recorded,
           NULL           as AccountingObjectID,
           NULL           as EmployeeID,
           NULL           as MaterialGoodsID,
           NULL           as RepositoryID,
           NULL           as BankAccountDetailID,
           NULL           as CreditCardID,
           a.ToolsID,
           NULL           as FixedAssetID,
           NULL           as CostSetID,
           NULL           as ExpenseItemID,
           NULL           as StatisticsCodeID,
           NULL           as BudgetItemID,
           NULL           as ContractID,
           NULL           as DepartmentID,
           NULL           as PaymentClauseID,
           NULL           as TransportMethodID,
           'TIAllocation' as RefTable
    from TIAllocationDetail a
             left join TIAllocation b on a.TIAllocationID = b.ID
             INNER JOIN
         dbo.EbOrganizationUnit c ON b.CompanyID = c.ID
             left join Type d on b.TypeID = d.ID
    union all
    select NEWID()       as ID,
           a.ID          as DetailID,
           b.ID          as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           NULL          as PostedDate,
           NULL          as CurrencyID,
           NULL          as TotalAmountOriginal,
           b.TotalAmount,
           b.Reason,
           a.Description,
           b.Recorded,
           NULL          as AccountingObjectID,
           NULL          as EmployeeID,
           NULL          as MaterialGoodsID,
           NULL          as RepositoryID,
           NULL          as BankAccountDetailID,
           NULL          as CreditCardID,
           NULL          as ToolsID,
           a.FixedAssetID,
           a.CostSetID,
           a.ExpenseItemID,
           NULL          as StatisticsCodeID,
           a.BudgetItemID,
           a.ContractID,
           a.DepartmentID,
           NULL          as PaymentClauseID,
           NULL          as TransportMethodID,
           'FAIncrement' as RefTable
    from FAIncrementDetail a
             left join FAIncrement b on a.FAIncrementID = b.ID
             left join Type c on b.TypeID = c.ID
    union all
    select NEWID()       as ID,
           a.ID          as DetailID,
           b.ID          as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           d.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           b.PostedDate,
           c.CurrencyID,
           b.TotalAmount as TotalAmountOriginal,
           b.TotalAmount,
           b.Reason,
           NULL          as Description,
           b.Recorded,
           NULL          as AccountingObjectID,
           NULL          as EmployeeID,
           NULL          as MaterialGoodsID,
           NULL          as RepositoryID,
           NULL          as BankAccountDetailID,
           NULL          as CreditCardID,
           NULL          as ToolsID,
           a.FixedAssetID,
           NULL          as CostSetID,
           NULL          as ExpenseItemID,
           NULL          as StatisticsCodeID,
           NULL          as BudgetItemID,
           NULL          as ContractID,
           a.DepartmentID,
           NULL          as PaymentClauseID,
           NULL          as TransportMethodID,
           'FADecrement' as RefTable
    from FADecrementDetail a
             left join FADecrement b on a.FADecrementID = b.ID
             INNER JOIN
         dbo.EbOrganizationUnit c ON b.CompanyID = c.ID
             left join Type d on b.TypeID = d.ID
    union all
    select NEWID()        as ID,
           a.ID           as DetailID,
           b.ID           as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           b.PostedDate,
           NULL           as CurrencyID,
           NULL           as TotalAmountOriginal,
           NULL           as TotalAmount,
           b.Reason,
           a.Description,
           b.Recorded,
           a.AccountingObjectID,
           NULL           as EmployeeID,
           NULL           as MaterialGoodsID,
           NULL           as RepositoryID,
           NULL           as BankAccountDetailID,
           NULL           as CreditCardID,
           NULL           as ToolsID,
           NULL           as FixedAssetID,
           a.CostSetID,
           a.ExpenseItemID,
           NULL           as StatisticsCodeID,
           a.BudgetItemID,
           a.ContractID,
           a.DepartmentID,
           NULL           as PaymentClauseID,
           NULL           as TransportMethodID,
           'FAAdjustment' as RefTable
    from FAAdjustmentDetail a
             left join FAAdjustment b on a.FAAdjustmentID = b.ID
             left join Type c on b.TypeID = c.ID
    union all
    select NEWID()      as ID,
           a.ID         as DetailID,
           b.ID         as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           NULL         as PostedDate,
           NULL         as CurrencyID,
           NULL         as TotalAmountOriginal,
           NULL         as TotalAmount,
           b.Reason,
           a.Description,
           b.Recorded,
           NULL         as AccountingObjectID,
           a.EmployeeID,
           NULL         as MaterialGoodsID,
           NULL         as RepositoryID,
           NULL         as BankAccountDetailID,
           NULL         as CreditCardID,
           NULL         as ToolsID,
           a.FixedAssetID,
           a.CostSetID,
           a.ExpenseItemID,
           NULL         as StatisticsCodeID,
           a.BudgetItemID,
           NULL         as ContractID,
           NULL         as DepartmentID,
           NULL         as PaymentClauseID,
           NULL         as TransportMethodID,
           'FATransfer' as RefTable
    from FATransferDetail a
             left join FATransfer b on a.FATransferID = b.ID
             left join Type c on b.TypeID = c.ID
    union all
    select NEWID()   as ID,
           a.ID      as DetailID,
           b.ID      as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           NULL      as PostedDate,
           NULL      as CurrencyID,
           NULL      as TotalAmountOriginal,
           NULL      as TotalAmount,
           NULL      as Reason,
           b.Description,
           NULL      as Recorded,
           NULL      as AccountingObjectID,
           NULL      as EmployeeID,
           NULL      as MaterialGoodsID,
           NULL      as RepositoryID,
           NULL      as BankAccountDetailID,
           NULL      as CreditCardID,
           NULL      as ToolsID,
           a.FixedAssetID,
           NULL      as CostSetID,
           NULL      as ExpenseItemID,
           NULL      as StatisticsCodeID,
           NULL      as BudgetItemID,
           NULL      as ContractID,
           a.DepartmentID,
           NULL      as PaymentClauseID,
           NULL      as TransportMethodID,
           'FAAudit' as RefTable
    from FAAuditDetail a
             left join FAAudit b on a.FAAuditID = b.ID
             left join Type c on b.TypeID = c.ID
    union all
    select NEWID()          as ID,
           a.ID             as DetailID,
           b.ID             as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           d.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           b.PostedDate,
           c.CurrencyID,
           b.TotalAmountOriginal,
           b.TotalAmount,
           b.Reason,
           NULL             as Description,
           b.Recorded,
           NULL             as AccountingObjectID,
           NULL             as EmployeeID,
           NULL             as MaterialGoodsID,
           NULL             as RepositoryID,
           NULL             as BankAccountDetailID,
           NULL             as CreditCardID,
           NULL             as ToolsID,
           NULL             as FixedAssetID,
           NULL             as CostSetID,
           NULL             as ExpenseItemID,
           NULL             as StatisticsCodeID,
           NULL             as BudgetItemID,
           NULL             as ContractID,
           NULL             as DepartmentID,
           NULL             as PaymentClauseID,
           NULL             as TransportMethodID,
           'FADepreciation' as RefTable
    from FADepreciationDetail a
             left join FADepreciation b on a.FADepreciationID = b.ID
             INNER JOIN
         dbo.EbOrganizationUnit c ON b.CompanyID = c.ID
             left join Type d on b.TypeID = d.ID
    union all
    select NEWID()         as ID,
           a.ID            as DetailID,
           b.ID            as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           c.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           b.PostedDate,
           b.CurrencyID,
           b.TotalAmountOriginal,
           b.TotalAmount,
           b.Reason,
           a.Description,
           b.Recorded,
           NULL            as AccountingObjectID,
           a.EmployeeID,
           NULL            as MaterialGoodsID,
           NULL            as RepositoryID,
           a.BankAccountDetailID,
           NULL            as CreditCardID,
           NULL            as ToolsID,
           NULL            as FixedAssetID,
           a.CostSetID,
           a.ExpenseItemID,
           a.StatisticsCodeID,
           a.BudgetItemID,
           a.ContractID,
           a.DepartmentID,
           NULL            as PaymentClauseID,
           NULL            as TransportMethodID,
           'GOtherVoucher' as RefTable
    from GOtherVoucherDetail a
             left join GOtherVoucher b on a.GOtherVoucherID = b.ID
             left join Type c on b.TypeID = c.ID
    union all
    select NEWID()        as ID,
           a.ID           as DetailID,
           b.ID           as ReferenceID,
           b.CompanyID,
           b.BranchID,
           b.TypeID,
           d.TypeGroupID,
           b.TypeLedger,
           b.NoMBook,
           b.NoFBook,
           b.Date,
           NULL           as PostedDate,
           c.CurrencyID,
           b.TotalAmount  as TotalAmountOriginal,
           b.TotalAmount,
           NULL           as Reason,
           b.Description,
           NULL           as Recorded,
           NULL           as AccountingObjectID,
           NULL           as EmployeeID,
           NULL           as MaterialGoodsID,
           NULL           as RepositoryID,
           NULL           as BankAccountDetailID,
           NULL           as CreditCardID,
           NULL           as ToolsID,
           NULL           as FixedAssetID,
           NULL           as CostSetID,
           NULL           as ExpenseItemID,
           NULL           as StatisticsCodeID,
           NULL           as BudgetItemID,
           NULL           as ContractID,
           NULL           as DepartmentID,
           NULL           as PaymentClauseID,
           NULL           as TransportMethodID,
           'GvoucherList' as RefTable
    from GvoucherListDetail a
             left join GvoucherList b on a.GVoucherListID = b.ID
             INNER JOIN
         dbo.EbOrganizationUnit c ON b.CompanyID = c.ID
             left join Type d on b.TypeID = d.ID
    union all
    select NEWID()      as ID,
           a.ID         as DetailID,
           a.ID         as ReferenceID,
           a.CompanyID,
           a.BranchID,
           a.TypeID,
           d.TypeGroupID,
           a.TypeLedger,
           'OPN'        as NoMBook,
           'OPN'        as NoFBook,
           a.PostedDate as Date,
           a.PostedDate,
           a.CurrencyID,
           NULL         as TotalAmountOriginal,
           NULL         as TotalAmount,
           NULL         as Reason,
           NULL         as Description,
           NULL         as Recorded,
           a.AccountingObjectID,
           NULL         as EmployeeID,
           NULL         as MaterialGoodsID,
           NULL         as RepositoryID,
           a.BankAccountDetailID,
           NULL         as CreditCardID,
           NULL         as ToolsID,
           NULL         as FixedAssetID,
           a.CostSetID,
           a.ExpenseItemID,
           a.StatisticsCodeID,
           a.BudgetItemID,
           a.ContractID,
           a.DepartmentID,
           NULL         as PaymentClauseID,
           NULL         as TransportMethodID,
           'OPAccount'  as RefTable
    from OPAccount a
             left join Type d on a.TypeID = d.ID
    union all
    select NEWID()           as ID,
           a.ID              as DetailID,
           a.ID              as ReferenceID,
           a.CompanyID,
           a.BranchID,
           a.TypeID,
           d.TypeGroupID,
           a.TypeLedger,
           'OPN'             as NoMBook,
           'OPN'             as NoFBook,
           a.PostedDate      as Date,
           a.PostedDate,
           a.CurrencyID,
           a.amountOriginal  as TotalAmountOriginal,
           a.amount          as TotalAmount,
           NULL              as Reason,
           NULL              as Description,
           NULL              as Recorded,
           NULL              as AccountingObjectID,
           NULL              as EmployeeID,
           a.MaterialGoodsID,
           a.RepositoryID,
           a.BankAccountDetailID,
           NULL              as CreditCardID,
           NULL              as ToolsID,
           NULL              as FixedAssetID,
           a.CostSetID,
           a.ExpenseItemID,
           a.StatisticsCodeID,
           a.BudgetItemID,
           a.ContractID,
           a.DepartmentID,
           NULL              as PaymentClauseID,
           NULL              as TransportMethodID,
           'OPMaterialGoods' as RefTable
    from OPMaterialGoods a
             left join Type d on a.TypeID = d.ID
go

